export type MenuItem = {
  to: string;
  label: string;
  /** Shown when the user holds any of these permissions. */
  perms: string[];
  /** ...and all of these as well (e.g. tender.margin for pages that show cost). */
  all?: string[];
  section: "Modules" | "Analytics" | "Masters" | "Settings" | "Administration";
};

export const MENU: MenuItem[] = [
  { to: "/dashboard", label: "Dashboard", perms: ["dashboard.company", "dashboard.sales", "dashboard.site", "dashboard.finance", "dashboard.purchase"], section: "Modules" },
  { to: "/analytics/sites", label: "Sites", perms: ["dashboard.company", "dashboard.site"], section: "Analytics" },
  { to: "/analytics/finance", label: "Finance", perms: ["dashboard.company", "dashboard.finance"], section: "Analytics" },
  { to: "/analytics/profitability", label: "Profitability", perms: ["dashboard.company", "dashboard.finance"], all: ["tender.margin"], section: "Analytics" },
  { to: "/analytics/purchase", label: "Purchase", perms: ["dashboard.company", "dashboard.purchase"], section: "Analytics" },
  { to: "/analytics/labour", label: "Labour", perms: ["dashboard.company", "dashboard.site"], section: "Analytics" },
  { to: "/analytics/strategy", label: "Strategy: win more sites", perms: ["dashboard.company", "dashboard.sales"], section: "Analytics" },
  { to: "/alerts", label: "Alerts", perms: ["dashboard.company", "dashboard.sales", "dashboard.site", "dashboard.finance", "dashboard.purchase"], section: "Analytics" },
  { to: "/reports", label: "Reports", perms: ["dashboard.company"], section: "Analytics" },
  { to: "/clients", label: "Clients", perms: ["clients.view"], section: "Masters" },
  { to: "/channels", label: "Channels", perms: ["clients.view"], section: "Masters" },
  { to: "/products", label: "Products", perms: ["library.view"], section: "Masters" },
  { to: "/systems", label: "Systems (rate calculator)", perms: ["library.view"], section: "Masters" },
  { to: "/rate-library", label: "Rate library", perms: ["library.view"], section: "Masters" },
  { to: "/tc-library", label: "T&C library", perms: ["library.view"], section: "Masters" },
  { to: "/vendors", label: "Vendors", perms: ["vendors.view"], section: "Masters" },
  { to: "/settings/company", label: "Company profile", perms: ["settings.company"], section: "Settings" },
  { to: "/settings/gstins", label: "GSTIN addresses", perms: ["settings.company"], section: "Settings" },
  { to: "/settings/bank-accounts", label: "Bank accounts", perms: ["settings.company", "finance.view"], section: "Settings" },
  { to: "/settings/categories", label: "Categories", perms: ["library.edit"], section: "Settings" },
  { to: "/settings/tags", label: "Tags", perms: ["library.edit"], section: "Settings" },
  { to: "/settings/units", label: "Units & conversions", perms: ["library.edit"], section: "Settings" },
  { to: "/settings/kylas", label: "Integrations › Kylas", perms: ["admin.settings"], section: "Settings" },
  { to: "/settings/purchase", label: "Purchase", perms: ["settings.company", "po.edit"], section: "Settings" },
  { to: "/settings/stage-templates", label: "Stage templates", perms: ["site.view"], section: "Settings" },
  { to: "/settings/quotation-library", label: "Quotation library", perms: ["quotation.view"], all: ["quotation.template.edit"], section: "Settings" },
  { to: "/settings/survey", label: "Site survey", perms: ["survey.view"], all: ["settings.company"], section: "Settings" },
  { to: "/leads", label: "Leads", perms: ["leads.view"], section: "Modules" },
  { to: "/quotations", label: "Quotations", perms: ["quotation.view"], section: "Modules" },
  { to: "/tenders", label: "Tenders", perms: ["tender.view"], section: "Modules" },
  { to: "/sites", label: "Sites", perms: ["site.view"], section: "Modules" },
  { to: "/snags", label: "Snags", perms: ["site.view"], section: "Modules" },
  { to: "/surveys", label: "Site surveys", perms: ["survey.view"], section: "Modules" },
  { to: "/indents", label: "Indents", perms: ["indent.view", "indent.create", "indent.approve"], section: "Modules" },
  { to: "/rfqs", label: "RFQs", perms: ["po.view"], section: "Modules" },
  { to: "/purchase-orders", label: "Purchase orders", perms: ["po.view"], section: "Modules" },
  { to: "/grns", label: "Goods receipts (GRN)", perms: ["grn.view"], section: "Modules" },
  { to: "/stores", label: "Stores & stock", perms: ["store.view"], section: "Modules" },
  { to: "/transfers", label: "Transfers", perms: ["store.view"], section: "Modules" },
  { to: "/freight", label: "Site freight", perms: ["po.view", "store.view"], section: "Modules" },
  { to: "/daily-reports", label: "Daily reports", perms: ["dpr.view"], section: "Modules" },
  { to: "/attendance", label: "Attendance", perms: ["labour.view"], section: "Modules" },
  { to: "/labour", label: "Labour", perms: ["labour.view"], section: "Masters" },
  { to: "/subcontractors", label: "Subcontractors", perms: ["subcon.view"], section: "Masters" },
  { to: "/assets", label: "Tools & equipment", perms: ["asset.view"], section: "Modules" },
  { to: "/settings/checklists", label: "Checklist templates", perms: ["inspection.view"], section: "Settings" },
  { to: "/billing", label: "Client billing", perms: ["billing.view"], section: "Modules" },
  { to: "/payables", label: "Payables", perms: ["payables.view"], section: "Modules" },
  { to: "/petty-cash", label: "Petty cash", perms: ["expense.create", "expense.approve"], section: "Modules" },
  { to: "/payroll", label: "Payroll & wages", perms: ["payroll.view", "payables.view"], section: "Modules" },
  { to: "/site-profit", label: "Site profit", perms: ["tender.margin"], section: "Modules" },
  { to: "/tally", label: "Tally export", perms: ["finance.export"], section: "Modules" },
  { to: "/settings/finance", label: "Finance", perms: ["billing.view", "payables.view", "payroll.view"], section: "Settings" },
  { to: "/admin/users", label: "Users", perms: ["admin.users"], section: "Administration" },
  { to: "/admin/roles", label: "Roles & permissions", perms: ["admin.roles"], section: "Administration" },
  { to: "/admin/audit", label: "Audit log", perms: ["audit.view"], section: "Administration" },
];
