"""M4 part 2: execution - DPR, labour and attendance, staff check-in, subcontractor work orders
and measurements, checklists and inspections, MOM, assets and equipment usage, site budget;
the "shortage" stock ledger entry; permissions and the seeded checklists.

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-07 12:05:53.641695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_templates",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_checklist_templates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_checklist_templates_name")),
    )
    op.create_table(
        "checklist_items",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=10), server_default="pass_fail", nullable=False),
        sa.Column("required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "type IN ('pass_fail', 'number', 'text', 'photo')",
            name=op.f("ck_checklist_items_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_checklist_items_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["checklist_templates.id"],
            name=op.f("fk_checklist_items_template_id_checklist_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_items")),
    )
    op.create_index(
        op.f("ix_checklist_items_template_id"), "checklist_items", ["template_id"], unique=False
    )
    op.create_table(
        "dprs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("weather", sa.String(length=60), nullable=True),
        sa.Column("work_done", sa.Text(), nullable=True),
        sa.Column("hindrances", sa.Text(), nullable=True),
        sa.Column("next_day_plan", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=12), server_default="draft", nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auto", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'acknowledged')", name=op.f("ck_dprs_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("fk_dprs_acknowledged_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_dprs_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_dprs_site_id_sites"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
            name=op.f("fk_dprs_submitted_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dprs")),
        sa.UniqueConstraint("site_id", "on_date", name=op.f("uq_dprs_site_id")),
    )
    op.create_index(op.f("ix_dprs_on_date"), "dprs", ["on_date"], unique=False)
    op.create_index(op.f("ix_dprs_site_id"), "dprs", ["site_id"], unique=False)
    op.create_table(
        "labour",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("trade", sa.String(length=12), server_default="helper", nullable=False),
        sa.Column("type", sa.String(length=14), server_default="own", nullable=False),
        sa.Column("subcontractor_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column(
            "daily_wage", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "ot_rate_per_hour",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("aadhaar_last4", sa.String(length=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(type = 'subcontractor') = (subcontractor_id IS NOT NULL)",
            name=op.f("ck_labour_subcontractor_set"),
        ),
        sa.CheckConstraint(
            "aadhaar_last4 ~ '^[0-9]{4}$'", name=op.f("ck_labour_aadhaar_last4_only")
        ),
        sa.CheckConstraint(
            "trade IN ('applicator', 'helper', 'mason', 'supervisor', 'other')",
            name=op.f("ck_labour_trade_valid"),
        ),
        sa.CheckConstraint("type IN ('own', 'subcontractor')", name=op.f("ck_labour_type_valid")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_labour_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_labour_site_id_sites"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["subcontractor_id"],
            ["vendors.id"],
            name=op.f("fk_labour_subcontractor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labour")),
    )
    op.create_index(op.f("ix_labour_name"), "labour", ["name"], unique=False)
    op.create_index(op.f("ix_labour_site_id"), "labour", ["site_id"], unique=False)
    op.create_index(
        op.f("ix_labour_subcontractor_id"), "labour", ["subcontractor_id"], unique=False
    )
    op.create_table(
        "moms",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("venue", sa.String(length=200), nullable=True),
        sa.Column(
            "attendee_user_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "attendee_others",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_moms_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_moms_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_moms")),
        sa.UniqueConstraint("code", name=op.f("uq_moms_code")),
    )
    op.create_index(op.f("ix_moms_site_id"), "moms", ["site_id"], unique=False)
    op.create_table(
        "site_budgets",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("head", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("source", sa.String(length=6), server_default="manual", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "head IN ('material', 'labour', 'subcontract', 'equipment', 'freight', 'other')",
            name=op.f("ck_site_budgets_head_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('tender', 'manual')", name=op.f("ck_site_budgets_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_site_budgets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_budgets_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_budgets")),
        sa.UniqueConstraint("site_id", "head", name=op.f("uq_site_budgets_site_id")),
    )
    op.create_index(op.f("ix_site_budgets_site_id"), "site_budgets", ["site_id"], unique=False)
    op.create_table(
        "site_costs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("head", sa.String(length=12), server_default="other", nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "head IN ('material', 'labour', 'subcontract', 'equipment', 'freight', 'other')",
            name=op.f("ck_site_costs_head_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_site_costs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_site_costs_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_costs")),
    )
    op.create_index(op.f("ix_site_costs_site_id"), "site_costs", ["site_id"], unique=False)
    op.create_table(
        "staff_attendance",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("check_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("check_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_staff_attendance_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_staff_attendance_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_attendance")),
    )
    op.create_index(
        op.f("ix_staff_attendance_on_date"), "staff_attendance", ["on_date"], unique=False
    )
    op.create_index(
        op.f("ix_staff_attendance_site_id"), "staff_attendance", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_staff_attendance_user_id"), "staff_attendance", ["user_id"], unique=False
    )
    op.create_table(
        "work_orders",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("subcontractor_id", sa.Integer(), nullable=False),
        sa.Column("material_by", sa.String(length=14), server_default="eespl", nullable=False),
        sa.Column(
            "retention_percent",
            sa.Numeric(precision=5, scale=2),
            server_default="5",
            nullable=False,
        ),
        sa.Column(
            "tds_percent", sa.Numeric(precision=5, scale=2), server_default="2", nullable=False
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("tc_template_id", sa.Integer(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="draft", nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "material_by IN ('eespl', 'subcontractor')",
            name=op.f("ck_work_orders_material_by_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'active', 'completed', 'closed')",
            name=op.f("ck_work_orders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_work_orders_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_work_orders_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_work_orders_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subcontractor_id"],
            ["vendors.id"],
            name=op.f("fk_work_orders_subcontractor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tc_template_id"],
            ["tc_templates.id"],
            name=op.f("fk_work_orders_tc_template_id_tc_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_orders")),
        sa.UniqueConstraint("code", name=op.f("uq_work_orders_code")),
    )
    op.create_index(op.f("ix_work_orders_site_id"), "work_orders", ["site_id"], unique=False)
    op.create_index(op.f("ix_work_orders_status"), "work_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_work_orders_subcontractor_id"), "work_orders", ["subcontractor_id"], unique=False
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=10), server_default="tool", nullable=False),
        sa.Column("make", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("serial_no", sa.String(length=100), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("purchase_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("ownership", sa.String(length=5), server_default="own", nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("rate_per_hour", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rate_per_day", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="available", nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("located_since", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "category IN ('tool', 'equipment', 'machine', 'vehicle')",
            name=op.f("ck_assets_category_valid"),
        ),
        sa.CheckConstraint(
            "ownership = 'own' OR vendor_id IS NOT NULL", name=op.f("ck_assets_hired_has_vendor")
        ),
        sa.CheckConstraint("ownership IN ('own', 'hired')", name=op.f("ck_assets_ownership_valid")),
        sa.CheckConstraint(
            "status IN ('available', 'at_site', 'repair', 'lost', 'disposed')",
            name=op.f("ck_assets_status_valid"),
        ),
        sa.CheckConstraint(
            "store_id IS NULL OR site_id IS NULL", name=op.f("ck_assets_one_location")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_assets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_assets_site_id_sites"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_assets_store_id_stores"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_assets_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("code", name=op.f("uq_assets_code")),
    )
    op.create_index(op.f("ix_assets_site_id"), "assets", ["site_id"], unique=False)
    op.create_index(op.f("ix_assets_status"), "assets", ["status"], unique=False)
    op.create_table(
        "attendance",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("labour_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("in_time", sa.Time(), nullable=True),
        sa.Column("out_time", sa.Time(), nullable=True),
        sa.Column("ot_hours", sa.Numeric(precision=4, scale=1), server_default="0", nullable=False),
        sa.Column(
            "daily_wage", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "ot_rate_per_hour",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("marked_by", sa.UUID(), nullable=True),
        sa.Column("photo_path", sa.String(length=400), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('present', 'half_day', 'absent')", name=op.f("ck_attendance_status_valid")
        ),
        sa.CheckConstraint(
            "ot_hours >= 0 AND ot_hours <= 16", name=op.f("ck_attendance_ot_hours_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_attendance_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["labour_id"],
            ["labour.id"],
            name=op.f("fk_attendance_labour_id_labour"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["marked_by"],
            ["users.id"],
            name=op.f("fk_attendance_marked_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_attendance_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance")),
        sa.UniqueConstraint("labour_id", "on_date", name=op.f("uq_attendance_labour_id")),
    )
    op.create_index(op.f("ix_attendance_on_date"), "attendance", ["on_date"], unique=False)
    op.create_index(op.f("ix_attendance_site_id"), "attendance", ["site_id"], unique=False)
    op.create_table(
        "dpr_photos",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("dpr_id", sa.Integer(), nullable=False),
        sa.Column("stored_path", sa.String(length=400), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("caption", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_dpr_photos_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dpr_id"], ["dprs.id"], name=op.f("fk_dpr_photos_dpr_id_dprs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dpr_photos")),
    )
    op.create_index(op.f("ix_dpr_photos_dpr_id"), "dpr_photos", ["dpr_id"], unique=False)
    op.create_table(
        "mom_points",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("mom_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("owner_name", sa.String(length=200), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=8), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'done', 'dropped')", name=op.f("ck_mom_points_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_mom_points_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mom_id"], ["moms.id"], name=op.f("fk_mom_points_mom_id_moms"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_mom_points_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mom_points")),
    )
    op.create_index(op.f("ix_mom_points_mom_id"), "mom_points", ["mom_id"], unique=False)
    op.create_table(
        "asset_movements",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("from_store_id", sa.Integer(), nullable=True),
        sa.Column("from_site_id", sa.Integer(), nullable=True),
        sa.Column("to_store_id", sa.Integer(), nullable=True),
        sa.Column("to_site_id", sa.Integer(), nullable=True),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("photo_path", sa.String(length=400), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_movements_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_asset_movements_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_site_id"],
            ["sites.id"],
            name=op.f("fk_asset_movements_from_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_store_id"],
            ["stores.id"],
            name=op.f("fk_asset_movements_from_store_id_stores"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_site_id"],
            ["sites.id"],
            name=op.f("fk_asset_movements_to_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_store_id"],
            ["stores.id"],
            name=op.f("fk_asset_movements_to_store_id_stores"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_movements")),
    )
    op.create_index(
        op.f("ix_asset_movements_asset_id"), "asset_movements", ["asset_id"], unique=False
    )
    op.create_table(
        "equipment_usage",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("basis", sa.String(length=4), server_default="day", nullable=False),
        sa.Column("quantity", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "fuel_litres", sa.Numeric(precision=8, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "fuel_cost", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("operator", sa.String(length=200), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("basis IN ('hour', 'day')", name=op.f("ck_equipment_usage_basis_valid")),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_equipment_usage_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_equipment_usage_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_equipment_usage_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_usage")),
    )
    op.create_index(
        op.f("ix_equipment_usage_asset_id"), "equipment_usage", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_usage_on_date"), "equipment_usage", ["on_date"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_usage_site_id"), "equipment_usage", ["site_id"], unique=False
    )
    op.create_table(
        "wo_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("wo_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("area_scope_id", sa.BigInteger(), nullable=True),
        sa.Column("boq_line_id", sa.BigInteger(), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_scope_id"],
            ["area_scopes.id"],
            name=op.f("fk_wo_lines_area_scope_id_area_scopes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["boq_line_id"],
            ["boq_lines.id"],
            name=op.f("fk_wo_lines_boq_line_id_boq_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_wo_lines_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["wo_id"],
            ["work_orders.id"],
            name=op.f("fk_wo_lines_wo_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wo_lines")),
    )
    op.create_index(op.f("ix_wo_lines_wo_id"), "wo_lines", ["wo_id"], unique=False)
    op.create_table(
        "inspections",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("task_id", sa.BigInteger(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("inspected_by", sa.UUID(), nullable=True),
        sa.Column("client_rep", sa.String(length=200), nullable=True),
        sa.Column("signature_path", sa.String(length=400), nullable=True),
        sa.Column(
            "photos", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "result IN ('pass', 'fail', 'pass_with_remarks')",
            name=op.f("ck_inspections_result_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_inspections_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["inspected_by"],
            ["users.id"],
            name=op.f("fk_inspections_inspected_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["site_nodes.id"],
            name=op.f("fk_inspections_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_inspections_site_id_sites"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_inspections_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["checklist_templates.id"],
            name=op.f("fk_inspections_template_id_checklist_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
        sa.UniqueConstraint("code", name=op.f("uq_inspections_code")),
    )
    op.create_index(op.f("ix_inspections_site_id"), "inspections", ["site_id"], unique=False)
    op.create_index(op.f("ix_inspections_task_id"), "inspections", ["task_id"], unique=False)
    op.create_table(
        "wo_measurements",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("line_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="recorded", nullable=False),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "photos", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('recorded', 'pending_approval', 'verified', 'rejected')",
            name=op.f("ck_wo_measurements_status_valid"),
        ),
        sa.CheckConstraint("qty > 0", name=op.f("ck_wo_measurements_qty_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_wo_measurements_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["wo_lines.id"],
            name=op.f("fk_wo_measurements_line_id_wo_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
            name=op.f("fk_wo_measurements_verified_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wo_measurements")),
    )
    op.create_index(
        op.f("ix_wo_measurements_line_id"), "wo_measurements", ["line_id"], unique=False
    )
    op.add_column(
        "company_profile",
        sa.Column("asset_overdue_days", sa.Integer(), server_default="30", nullable=False),
    )
    op.add_column(
        "stage_template_steps", sa.Column("checklist_template_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_stage_template_steps_checklist_template_id_checklist_templates"),
        "stage_template_steps",
        "checklist_templates",
        ["checklist_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stage_template_steps_checklist_template_id_checklist_templates"),
        "stage_template_steps",
        type_="foreignkey",
    )
    op.drop_column("stage_template_steps", "checklist_template_id")
    op.drop_column("company_profile", "asset_overdue_days")
    op.drop_index(op.f("ix_wo_measurements_line_id"), table_name="wo_measurements")
    op.drop_table("wo_measurements")
    op.drop_index(op.f("ix_inspections_task_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_site_id"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(op.f("ix_wo_lines_wo_id"), table_name="wo_lines")
    op.drop_table("wo_lines")
    op.drop_index(op.f("ix_equipment_usage_site_id"), table_name="equipment_usage")
    op.drop_index(op.f("ix_equipment_usage_on_date"), table_name="equipment_usage")
    op.drop_index(op.f("ix_equipment_usage_asset_id"), table_name="equipment_usage")
    op.drop_table("equipment_usage")
    op.drop_index(op.f("ix_asset_movements_asset_id"), table_name="asset_movements")
    op.drop_table("asset_movements")
    op.drop_index(op.f("ix_mom_points_mom_id"), table_name="mom_points")
    op.drop_table("mom_points")
    op.drop_index(op.f("ix_dpr_photos_dpr_id"), table_name="dpr_photos")
    op.drop_table("dpr_photos")
    op.drop_index(op.f("ix_attendance_site_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_on_date"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_assets_status"), table_name="assets")
    op.drop_index(op.f("ix_assets_site_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_work_orders_subcontractor_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_status"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_site_id"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index(op.f("ix_staff_attendance_user_id"), table_name="staff_attendance")
    op.drop_index(op.f("ix_staff_attendance_site_id"), table_name="staff_attendance")
    op.drop_index(op.f("ix_staff_attendance_on_date"), table_name="staff_attendance")
    op.drop_table("staff_attendance")
    op.drop_index(op.f("ix_site_costs_site_id"), table_name="site_costs")
    op.drop_table("site_costs")
    op.drop_index(op.f("ix_site_budgets_site_id"), table_name="site_budgets")
    op.drop_table("site_budgets")
    op.drop_index(op.f("ix_moms_site_id"), table_name="moms")
    op.drop_table("moms")
    op.drop_index(op.f("ix_labour_subcontractor_id"), table_name="labour")
    op.drop_index(op.f("ix_labour_site_id"), table_name="labour")
    op.drop_index(op.f("ix_labour_name"), table_name="labour")
    op.drop_table("labour")
    op.drop_index(op.f("ix_dprs_site_id"), table_name="dprs")
    op.drop_index(op.f("ix_dprs_on_date"), table_name="dprs")
    op.drop_table("dprs")
    op.drop_index(op.f("ix_checklist_items_template_id"), table_name="checklist_items")
    op.drop_table("checklist_items")
    op.drop_table("checklist_templates")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("dpr.view", "execution", "View daily progress reports"),
    ("dpr.edit", "execution", "Write and submit daily progress reports"),
    ("labour.view", "execution", "View labour, attendance and muster rolls"),
    ("labour.edit", "execution", "Mark attendance, keep the labour list"),
    ("subcon.view", "execution", "View subcontractor work orders and measurements"),
    ("subcon.edit", "execution", "Create work orders, record measurements"),
    ("subcon.approve", "execution", "Approve work orders and over-measurement"),
    ("inspection.view", "execution", "View inspections and minutes of meeting"),
    ("inspection.edit", "execution", "Carry out inspections, write minutes of meeting"),
    ("asset.view", "execution", "View tools, assets and equipment"),
    ("asset.edit", "execution", "Move assets, record equipment usage"),
    ("budget.view", "execution", "View site budget vs actual"),
    ("budget.edit", "execution", "Set site budgets, enter other costs"),
]
CODES = [c for c, _, _ in NEW_PERMISSIONS]
GRANTS = {
    "super_admin": dict.fromkeys(CODES, "all"),
    "office_admin": dict.fromkeys(CODES, "all"),
    "site_supervisor": dict.fromkeys(
        [
            "dpr.view",
            "dpr.edit",
            "labour.view",
            "labour.edit",
            "inspection.view",
            "inspection.edit",
            "asset.view",
        ],
        "assigned",
    ),
    "accounts": dict.fromkeys(
        ["dpr.view", "labour.view", "subcon.view", "inspection.view", "asset.view", "budget.view"],
        "all",
    ),
    "sales": {"dpr.view": "assigned"},
    "store_purchase": dict.fromkeys(["asset.view", "asset.edit"], "all"),
}

P, N, T, F = "pass_fail", "number", "text", "photo"
CHECKLISTS = {
    "Pre-waterproofing surface check": [
        ("Surface clean, free of dust, oil and laitance", P, True),
        ("No honeycombing or cracks (or repaired and cured)", P, True),
        ("Surface moisture (%)", N, True),
        ("Slopes towards the outlets checked", P, True),
        ("Corners coved / fillets done", P, True),
        ("Photo of the prepared surface", F, True),
        ("Remarks", T, False),
    ],
    "Ponding test": [
        ("Outlets plugged and edges bunded", P, True),
        ("Water depth (mm)", N, True),
        ("Duration (hours)", N, True),
        ("No leakage or dampness below at the end of the test", P, True),
        ("Photo of the ponding", F, True),
        ("Remarks", T, False),
    ],
    "Water tank test": [
        ("Tank filled to the overflow level", P, True),
        ("Duration (hours)", N, True),
        ("Level drop (mm)", N, True),
        ("No leakage or dampness on the outer face", P, True),
        ("Photo of the filled tank", F, True),
        ("Remarks", T, False),
    ],
    "Membrane lap check": [
        ("Laps at least 100 mm everywhere", P, True),
        ("Smallest lap measured (mm)", N, True),
        ("Laps sealed, no wrinkles or bubbles", P, True),
        ("Terminations fixed and sealed", P, True),
        ("Photo of a lap", F, True),
        ("Remarks", T, False),
    ],
    "Final handover": [
        ("All areas complete as per the scope", P, True),
        ("Protection screed / tiles done where required", P, True),
        ("Site cleaned, debris removed", P, True),
        ("Guarantee handed over", P, True),
        ("Client representative's remarks", T, False),
        ("Handover photo", F, True),
    ],
}


def _q(text: str) -> str:
    return text.replace("'", "''")


def _grant(role: str, code: str, scope: str) -> None:
    op.execute(
        "INSERT INTO role_permissions (role_id, permission_code, scope) "
        f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
        f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
    )


def _ledger_refs(refs: str) -> None:
    op.drop_constraint(op.f("ck_stock_ledger_ref_type_valid"), "stock_ledger", type_="check")
    op.create_check_constraint("ref_type_valid", "stock_ledger", f"ref_type IN ({refs})")


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            _grant(role, code, scope)
    for name, items in CHECKLISTS.items():
        op.execute(f"INSERT INTO checklist_templates (name) VALUES ('{_q(name)}')")
        for i, (text, kind, required) in enumerate(items, start=1):
            op.execute(
                "INSERT INTO checklist_items (template_id, sort_order, text, type, required) "
                f"SELECT id, {i}, '{_q(text)}', '{kind}', {str(required).lower()} "
                f"FROM checklist_templates WHERE name = '{_q(name)}'"
            )
    _ledger_refs(
        "'grn', 'transfer_out', 'transfer_in', 'shortage', 'issue', 'return', 'adjust', 'opening'"
    )
    op.execute(REBUILD_PO_FREIGHT)
    op.execute(BACKFILL_SHORTAGES)


# PO freight used to be charged in full when the PO was approved; it now follows the GRNs. Rebuild
# the existing PO freight entries that way: each approved GRN carries its received value's share.
REBUILD_PO_FREIGHT = """
DELETE FROM freight_entries WHERE source = 'po';
INSERT INTO freight_entries (source, po_id, grn_id, site_id, direction, on_date, amount,
                             gst_percent,
                             transporter, to_place, remark, created_by)
SELECT 'po', po.id, g.id, x.site_id, 'inbound', g.received_at,
       round(c.amount * x.value / po.taxable, 2), c.gst_percent, v.name, st.name,
       coalesce(c.description, 'Freight') || ' (' || g.code || ')', g.created_by
FROM (
    SELECT gl.grn_id, pl.po_id, coalesce(i.site_id, s2.site_id) AS site_id,
           sum(gl.accepted_qty * gl.rate) AS value
    FROM grn_lines gl
    JOIN po_lines pl ON pl.id = gl.po_line_id
    JOIN purchase_orders p2 ON p2.id = pl.po_id
    JOIN stores s2 ON s2.id = p2.store_id
    LEFT JOIN indent_lines il ON il.id = pl.indent_line_id
    LEFT JOIN indents i ON i.id = il.indent_id
    WHERE gl.accepted_qty > 0
    GROUP BY gl.grn_id, pl.po_id, coalesce(i.site_id, s2.site_id)
) x
JOIN grns g ON g.id = x.grn_id AND g.status = 'approved'
JOIN purchase_orders po ON po.id = x.po_id AND po.taxable > 0
JOIN po_charges c ON c.po_id = po.id AND c.kind = 'freight' AND c.amount > 0
JOIN vendors v ON v.id = po.vendor_id
JOIN stores st ON st.id = po.store_id
"""


# Transfer shortages received before the 'shortage' entry existed: book them now (the full
# quantity in, the shortage out), so their value is charged to the receiving site too.
BACKFILL_SHORTAGES = """
INSERT INTO stock_ledger (store_id, product_id, qty, unit, rate, value, ref_type, ref_id, note,
                          at, by)
SELECT t.to_store_id, tl.product_id, q.qty, p.unit, coalesce(tl.rate, 0),
       round(q.qty * coalesce(tl.rate, 0), 2), q.ref_type, t.id, q.note, t.received_at,
       t.received_by
FROM transfers t
JOIN transfer_lines tl ON tl.transfer_id = t.id AND tl.shortage_qty > 0
JOIN products p ON p.id = tl.product_id
CROSS JOIN LATERAL (
    VALUES (tl.shortage_qty, 'transfer_in', t.code),
           (-tl.shortage_qty, 'shortage', t.code || ': ' || coalesce(tl.shortage_reason, ''))
) AS q(qty, ref_type, note)
WHERE t.status = 'received'
  AND NOT EXISTS (SELECT 1 FROM stock_ledger s WHERE s.ref_type = 'shortage' AND s.ref_id = t.id)
"""


def _unseed() -> None:
    op.execute("DELETE FROM stock_ledger WHERE ref_type = 'shortage'")
    _ledger_refs("'grn', 'transfer_out', 'transfer_in', 'issue', 'return', 'adjust', 'opening'")
    op.execute("DELETE FROM permissions WHERE code IN (" + ", ".join(f"'{c}'" for c in CODES) + ")")
