"""Carry-over fixes: products.hsn_code (HSN / SAC on the PO) and the freight SAC setting.

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-07 13:25:07.336602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_profile",
        sa.Column("freight_sac", sa.String(length=8), server_default="9965", nullable=False),
    )
    op.add_column("products", sa.Column("hsn_code", sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "hsn_code")
    op.drop_column("company_profile", "freight_sac")
    # ### end Alembic commands ###
