"""M5 part 1: finance - client contracts, RA bills, tax invoices, receipts, vendor bills and
payments, subcontractor RA bills, petty cash, payroll, labour wages, Tally export; permissions,
the finance settings row and the expense categories.

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-07 13:35:32.599323

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_categories",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("budget_head", sa.String(length=12), server_default="other", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "budget_head IN ('material', 'labour', 'subcontract', 'equipment', 'freight', 'other')",
            name=op.f("ck_expense_categories_head_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_expense_categories_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_expense_categories_name")),
    )
    op.create_table(
        "finance_settings",
        sa.Column("id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("invoice_prefix", sa.String(length=6), server_default="EESPL", nullable=False),
        sa.Column("works_sac", sa.String(length=8), server_default="9954", nullable=False),
        sa.Column(
            "match_tolerance_percent",
            sa.Numeric(precision=6, scale=3),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "payment_approval_limit",
            sa.Numeric(precision=14, scale=2),
            server_default="100000",
            nullable=False,
        ),
        sa.Column(
            "expense_photo_limit",
            sa.Numeric(precision=14, scale=2),
            server_default="500",
            nullable=False,
        ),
        sa.Column("tds_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "pf_percent", sa.Numeric(precision=6, scale=3), server_default="12", nullable=False
        ),
        sa.Column(
            "pf_wage_cap", sa.Numeric(precision=14, scale=2), server_default="15000", nullable=False
        ),
        sa.Column(
            "esi_threshold",
            sa.Numeric(precision=14, scale=2),
            server_default="21000",
            nullable=False,
        ),
        sa.Column(
            "esi_employee_percent",
            sa.Numeric(precision=6, scale=3),
            server_default="0.75",
            nullable=False,
        ),
        sa.Column(
            "esi_employer_percent",
            sa.Numeric(precision=6, scale=3),
            server_default="3.25",
            nullable=False,
        ),
        sa.Column("pt_slabs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tally_ledgers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "party_ledgers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("id = 1", name=op.f("ck_finance_settings_single_row")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_finance_settings_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_settings")),
    )
    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=8), server_default="draft", nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.UUID(), nullable=True),
        sa.Column("paid_mode", sa.String(length=8), nullable=True),
        sa.Column("paid_ref", sa.String(length=60), nullable=True),
        sa.Column("tally_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'locked')", name=op.f("ck_payroll_runs_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_payroll_runs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["locked_by"],
            ["users.id"],
            name=op.f("fk_payroll_runs_locked_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_runs")),
        sa.UniqueConstraint("month", name=op.f("uq_payroll_runs_month")),
    )
    op.create_table(
        "petty_cash_accounts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_petty_cash_accounts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_petty_cash_accounts_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_petty_cash_accounts")),
        sa.UniqueConstraint("user_id", name=op.f("uq_petty_cash_accounts_user_id")),
    )
    op.create_table(
        "salary_structures",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("basic", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("hra", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "other_allowance", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("pf", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("esi", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("pt_state", sa.String(length=50), server_default="Gujarat", nullable=False),
        sa.Column(
            "monthly_ctc", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_salary_structures_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_salary_structures_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salary_structures")),
        sa.UniqueConstraint("user_id", "effective_from", name=op.f("uq_salary_structures_user_id")),
    )
    op.create_index(
        op.f("ix_salary_structures_user_id"), "salary_structures", ["user_id"], unique=False
    )
    op.create_table(
        "tally_exports",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("vouchers", sa.Integer(), nullable=False),
        sa.Column("include_exported", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_tally_exports_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tally_exports")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("ref_no", sa.String(length=60), nullable=True),
        sa.Column("bank_account_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="paid", nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("tally_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "mode IN ('neft', 'rtgs', 'cheque', 'upi', 'cash')", name=op.f("ck_payments_mode_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending_approval', 'paid', 'cancelled')",
            name=op.f("ck_payments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_payments_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["company_bank_accounts.id"],
            name=op.f("fk_payments_bank_account_id_company_bank_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_payments_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_payments_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("number", name=op.f("uq_payments_number")),
    )
    op.create_index(op.f("ix_payments_on_date"), "payments", ["on_date"], unique=False)
    op.create_index(op.f("ix_payments_vendor_id"), "payments", ["vendor_id"], unique=False)
    op.create_table(
        "payslips",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("structure_id", sa.Integer(), nullable=False),
        sa.Column("days_in_month", sa.Integer(), nullable=False),
        sa.Column("worked_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "leave_days", sa.Numeric(precision=5, scale=1), server_default="0", nullable=False
        ),
        sa.Column("lop_days", sa.Numeric(precision=5, scale=1), server_default="0", nullable=False),
        sa.Column("paid_days", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("basic", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("hra", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "other_allowance", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("gross", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "pf_employee", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "pf_employer", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "esi_employee", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "esi_employer", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("pt", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "advance_recovery",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("net", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "site_days",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_payslips_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["payroll_runs.id"],
            name=op.f("fk_payslips_run_id_payroll_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["salary_structures.id"],
            name=op.f("fk_payslips_structure_id_salary_structures"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_payslips_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payslips")),
        sa.UniqueConstraint("run_id", "user_id", name=op.f("uq_payslips_run_id")),
    )
    op.create_index(op.f("ix_payslips_run_id"), "payslips", ["run_id"], unique=False)
    op.create_table(
        "staff_advances",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("recovered_in_payslip_id", sa.Integer(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_staff_advances_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recovered_in_payslip_id"],
            ["payslips.id"],
            name=op.f("fk_staff_advances_recovered_in_payslip_id_payslips"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_staff_advances_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_advances")),
    )
    op.create_index(op.f("ix_staff_advances_user_id"), "staff_advances", ["user_id"], unique=False)
    op.create_table(
        "client_contracts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("tender_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column(
            "contract_value", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "retention_percent",
            sa.Numeric(precision=6, scale=3),
            server_default="5",
            nullable=False,
        ),
        sa.Column(
            "advance_amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "advance_recovery_percent",
            sa.Numeric(precision=6, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "tds_percent", sa.Numeric(precision=6, scale=3), server_default="2", nullable=False
        ),
        sa.Column(
            "gst_tds_percent", sa.Numeric(precision=6, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "gst_percent", sa.Numeric(precision=6, scale=3), server_default="18", nullable=False
        ),
        sa.Column("sac", sa.String(length=8), server_default="9954", nullable=False),
        sa.Column("place_of_supply", sa.String(length=100), nullable=True),
        sa.Column("client_gstin", sa.String(length=15), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("from_gstin_id", sa.Integer(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_contracts_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_client_contracts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_gstin_id"],
            ["company_gstins.id"],
            name=op.f("fk_client_contracts_from_gstin_id_company_gstins"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_client_contracts_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
            name=op.f("fk_client_contracts_tender_id_tenders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_contracts")),
        sa.UniqueConstraint("site_id", name=op.f("uq_client_contracts_site_id")),
    )
    op.create_table(
        "petty_cash_entries",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("paid_to", sa.String(length=200), nullable=True),
        sa.Column("mode", sa.String(length=8), server_default="cash", nullable=False),
        sa.Column("bank_account_id", sa.Integer(), nullable=True),
        sa.Column("photo_path", sa.String(length=400), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="approved", nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("tally_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('advance', 'expense', 'settlement')",
            name=op.f("ck_petty_cash_entries_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('submitted', 'approved', 'rejected')",
            name=op.f("ck_petty_cash_entries_status_valid"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_petty_cash_entries_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["petty_cash_accounts.id"],
            name=op.f("fk_petty_cash_entries_account_id_petty_cash_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_petty_cash_entries_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["company_bank_accounts.id"],
            name=op.f("fk_petty_cash_entries_bank_account_id_company_bank_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expense_categories.id"],
            name=op.f("fk_petty_cash_entries_category_id_expense_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_petty_cash_entries_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_petty_cash_entries_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_petty_cash_entries")),
        sa.UniqueConstraint("number", name=op.f("uq_petty_cash_entries_number")),
    )
    op.create_index(
        op.f("ix_petty_cash_entries_account_id"), "petty_cash_entries", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_petty_cash_entries_on_date"), "petty_cash_entries", ["on_date"], unique=False
    )
    op.create_index(
        op.f("ix_petty_cash_entries_site_id"), "petty_cash_entries", ["site_id"], unique=False
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("ref_no", sa.String(length=60), nullable=True),
        sa.Column("bank_account_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "tds_amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "gst_tds_amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "write_off", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("write_off_reason", sa.Text(), nullable=True),
        sa.Column("is_advance", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_retention", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("tally_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "mode IN ('neft', 'rtgs', 'cheque', 'upi', 'cash')", name=op.f("ck_receipts_mode_valid")
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["company_bank_accounts.id"],
            name=op.f("fk_receipts_bank_account_id_company_bank_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_receipts_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_receipts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_receipts_site_id_sites"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("number", name=op.f("uq_receipts_number")),
    )
    op.create_index(op.f("ix_receipts_client_id"), "receipts", ["client_id"], unique=False)
    op.create_index(op.f("ix_receipts_on_date"), "receipts", ["on_date"], unique=False)
    op.create_table(
        "retention_releases",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_retention_releases_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_retention_releases_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_releases")),
    )
    op.create_index(
        op.f("ix_retention_releases_site_id"), "retention_releases", ["site_id"], unique=False
    )
    op.create_table(
        "vendor_bills",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=12), server_default="material", nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("bill_no", sa.String(length=60), nullable=False),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("interstate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("itc_eligible", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("taxable", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "round_off", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("total", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("tds_section", sa.String(length=8), nullable=True),
        sa.Column(
            "tds_percent", sa.Numeric(precision=6, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "tds_amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("payable", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="draft", nullable=False),
        sa.Column(
            "match_issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("tally_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('material', 'service', 'freight', 'subcontract', 'retention')",
            name=op.f("ck_vendor_bills_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'partly_paid', 'paid', 'cancelled')",
            name=op.f("ck_vendor_bills_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_vendor_bills_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_vendor_bills_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_vendor_bills_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_bills_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bills")),
        sa.UniqueConstraint("number", name=op.f("uq_vendor_bills_number")),
    )
    op.create_index(op.f("ix_vendor_bills_due_date"), "vendor_bills", ["due_date"], unique=False)
    op.create_index(op.f("ix_vendor_bills_site_id"), "vendor_bills", ["site_id"], unique=False)
    op.create_index(op.f("ix_vendor_bills_status"), "vendor_bills", ["status"], unique=False)
    op.create_index(op.f("ix_vendor_bills_vendor_id"), "vendor_bills", ["vendor_id"], unique=False)
    op.create_table(
        "contract_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("boq_line_id", sa.BigInteger(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("item_no", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("is_extra", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_contract_lines_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["boq_line_id"],
            ["boq_lines.id"],
            name=op.f("fk_contract_lines_boq_line_id_boq_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["client_contracts.id"],
            name=op.f("fk_contract_lines_contract_id_client_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_contract_lines_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_lines")),
    )
    op.create_index(
        op.f("ix_contract_lines_contract_id"), "contract_lines", ["contract_id"], unique=False
    )
    op.create_table(
        "labour_wage_payments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("labour_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("period_from", sa.Date(), nullable=False),
        sa.Column("period_to", sa.Date(), nullable=False),
        sa.Column("days", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("ot_hours", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("wage_due", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "advances_recovered",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("net", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=4), server_default="due", nullable=False),
        sa.Column("paid_on", sa.Date(), nullable=True),
        sa.Column("mode", sa.String(length=8), nullable=True),
        sa.Column("ref_no", sa.String(length=60), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('due', 'paid')", name=op.f("ck_labour_wage_payments_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_labour_wage_payments_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["labour_id"],
            ["labour.id"],
            name=op.f("fk_labour_wage_payments_labour_id_labour"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_labour_wage_payments_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labour_wage_payments")),
        sa.UniqueConstraint(
            "labour_id", "site_id", "period_from", name=op.f("uq_labour_wage_payments_labour_id")
        ),
    )
    op.create_index(
        op.f("ix_labour_wage_payments_labour_id"),
        "labour_wage_payments",
        ["labour_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_labour_wage_payments_site_id"), "labour_wage_payments", ["site_id"], unique=False
    )
    op.create_table(
        "payment_allocations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=False),
        sa.Column("vendor_bill_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_allocations_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_bill_id"],
            ["vendor_bills.id"],
            name=op.f("fk_payment_allocations_vendor_bill_id_vendor_bills"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_allocations")),
    )
    op.create_index(
        op.f("ix_payment_allocations_payment_id"),
        "payment_allocations",
        ["payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_allocations_vendor_bill_id"),
        "payment_allocations",
        ["vendor_bill_id"],
        unique=False,
    )
    op.create_table(
        "ra_bills",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("period_from", sa.Date(), nullable=True),
        sa.Column("period_to", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="draft", nullable=False),
        sa.Column("gross", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("certified_gross", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "retention", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "advance_recovery",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "other_deduction", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("other_deduction_remark", sa.Text(), nullable=True),
        sa.Column("net", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("certified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("certified_by_client", sa.String(length=200), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'certified', 'invoiced', 'cancelled')",
            name=op.f("ck_ra_bills_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["client_contracts.id"],
            name=op.f("fk_ra_bills_contract_id_client_contracts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_ra_bills_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_ra_bills_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ra_bills")),
        sa.UniqueConstraint("code", name=op.f("uq_ra_bills_code")),
        sa.UniqueConstraint("contract_id", "seq", name=op.f("uq_ra_bills_contract_id")),
    )
    op.create_index(op.f("ix_ra_bills_contract_id"), "ra_bills", ["contract_id"], unique=False)
    op.create_index(op.f("ix_ra_bills_site_id"), "ra_bills", ["site_id"], unique=False)
    op.create_index(op.f("ix_ra_bills_status"), "ra_bills", ["status"], unique=False)
    op.create_table(
        "subcon_bills",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("wo_id", sa.Integer(), nullable=False),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("gross", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "retention", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("tds", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "material_recovery",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "advance_recovery",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "gst_percent", sa.Numeric(precision=6, scale=3), server_default="0", nullable=False
        ),
        sa.Column("gst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("net", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=10), server_default="draft", nullable=False),
        sa.Column("vendor_bill_id", sa.Integer(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'cancelled')",
            name=op.f("ck_subcon_bills_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_subcon_bills_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_bill_id"],
            ["vendor_bills.id"],
            name=op.f("fk_subcon_bills_vendor_bill_id_vendor_bills"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["wo_id"],
            ["work_orders.id"],
            name=op.f("fk_subcon_bills_wo_id_work_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subcon_bills")),
        sa.UniqueConstraint("number", name=op.f("uq_subcon_bills_number")),
    )
    op.create_index(op.f("ix_subcon_bills_wo_id"), "subcon_bills", ["wo_id"], unique=False)
    op.create_table(
        "subcon_retention_releases",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("wo_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vendor_bill_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_subcon_retention_releases_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_bill_id"],
            ["vendor_bills.id"],
            name=op.f("fk_subcon_retention_releases_vendor_bill_id_vendor_bills"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["wo_id"],
            ["work_orders.id"],
            name=op.f("fk_subcon_retention_releases_wo_id_work_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subcon_retention_releases")),
    )
    op.create_index(
        op.f("ix_subcon_retention_releases_wo_id"),
        "subcon_retention_releases",
        ["wo_id"],
        unique=False,
    )
    op.create_table(
        "labour_advances",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("labour_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("recovered_in_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_labour_advances_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["labour_id"],
            ["labour.id"],
            name=op.f("fk_labour_advances_labour_id_labour"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovered_in_id"],
            ["labour_wage_payments.id"],
            name=op.f("fk_labour_advances_recovered_in_id_labour_wage_payments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_labour_advances_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labour_advances")),
    )
    op.create_index(
        op.f("ix_labour_advances_labour_id"), "labour_advances", ["labour_id"], unique=False
    )
    op.create_index(
        op.f("ix_labour_advances_site_id"), "labour_advances", ["site_id"], unique=False
    )
    op.create_table(
        "ra_bill_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("ra_bill_id", sa.Integer(), nullable=False),
        sa.Column("contract_line_id", sa.Integer(), nullable=False),
        sa.Column(
            "previous_qty", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "suggested_qty", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False
        ),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("certified_qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("certified_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_line_id"],
            ["contract_lines.id"],
            name=op.f("fk_ra_bill_lines_contract_line_id_contract_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ra_bill_id"],
            ["ra_bills.id"],
            name=op.f("fk_ra_bill_lines_ra_bill_id_ra_bills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ra_bill_lines")),
    )
    op.create_index(
        op.f("ix_ra_bill_lines_ra_bill_id"), "ra_bill_lines", ["ra_bill_id"], unique=False
    )
    op.create_table(
        "tax_invoices",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=12), server_default="invoice", nullable=False),
        sa.Column("status", sa.String(length=10), server_default="issued", nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=True),
        sa.Column("ra_bill_id", sa.Integer(), nullable=True),
        sa.Column("against_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("client_gstin", sa.String(length=15), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("place_of_supply", sa.String(length=100), nullable=True),
        sa.Column("from_gstin_id", sa.Integer(), nullable=True),
        sa.Column("interstate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("taxable", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "round_off", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("total", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "retention", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "advance_recovery",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "other_deduction", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("tally_exported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('invoice', 'credit_note')", name=op.f("ck_tax_invoices_kind_valid")
        ),
        sa.CheckConstraint(
            "status IN ('issued', 'cancelled')", name=op.f("ck_tax_invoices_status_valid")
        ),
        sa.CheckConstraint("length(number) <= 16", name=op.f("ck_tax_invoices_number_16_chars")),
        sa.ForeignKeyConstraint(
            ["against_id"],
            ["tax_invoices.id"],
            name=op.f("fk_tax_invoices_against_id_tax_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_tax_invoices_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["client_contracts.id"],
            name=op.f("fk_tax_invoices_contract_id_client_contracts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_tax_invoices_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_gstin_id"],
            ["company_gstins.id"],
            name=op.f("fk_tax_invoices_from_gstin_id_company_gstins"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ra_bill_id"],
            ["ra_bills.id"],
            name=op.f("fk_tax_invoices_ra_bill_id_ra_bills"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_tax_invoices_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_tax_invoices_number")),
        sa.UniqueConstraint("ra_bill_id", name=op.f("uq_tax_invoices_ra_bill_id")),
    )
    op.create_index(op.f("ix_tax_invoices_client_id"), "tax_invoices", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_tax_invoices_invoice_date"), "tax_invoices", ["invoice_date"], unique=False
    )
    op.create_index(op.f("ix_tax_invoices_site_id"), "tax_invoices", ["site_id"], unique=False)
    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sac", sa.String(length=8), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_percent", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["tax_invoices.id"],
            name=op.f("fk_invoice_lines_invoice_id_tax_invoices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
    )
    op.create_index(
        op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"], unique=False
    )
    op.create_table(
        "receipt_allocations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["tax_invoices.id"],
            name=op.f("fk_receipt_allocations_invoice_id_tax_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_allocations_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_allocations")),
    )
    op.create_index(
        op.f("ix_receipt_allocations_invoice_id"),
        "receipt_allocations",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receipt_allocations_receipt_id"),
        "receipt_allocations",
        ["receipt_id"],
        unique=False,
    )
    op.create_table(
        "vendor_bill_grns",
        sa.Column("vendor_bill_id", sa.Integer(), nullable=False),
        sa.Column("grn_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grn_id"],
            ["grns.id"],
            name=op.f("fk_vendor_bill_grns_grn_id_grns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_bill_id"],
            ["vendor_bills.id"],
            name=op.f("fk_vendor_bill_grns_vendor_bill_id_vendor_bills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("vendor_bill_id", "grn_id", name=op.f("pk_vendor_bill_grns")),
    )
    op.create_table(
        "subcon_bill_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("subcon_bill_id", sa.Integer(), nullable=False),
        sa.Column("measurement_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["measurement_id"],
            ["wo_measurements.id"],
            name=op.f("fk_subcon_bill_lines_measurement_id_wo_measurements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subcon_bill_id"],
            ["subcon_bills.id"],
            name=op.f("fk_subcon_bill_lines_subcon_bill_id_subcon_bills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subcon_bill_lines")),
        sa.UniqueConstraint("measurement_id", name=op.f("uq_subcon_bill_lines_measurement_id")),
    )
    op.create_index(
        op.f("ix_subcon_bill_lines_subcon_bill_id"),
        "subcon_bill_lines",
        ["subcon_bill_id"],
        unique=False,
    )
    op.create_table(
        "vendor_bill_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("vendor_bill_id", sa.Integer(), nullable=False),
        sa.Column("grn_line_id", sa.Integer(), nullable=True),
        sa.Column("po_line_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("hsn_code", sa.String(length=8), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), server_default="1", nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "gst_percent", sa.Numeric(precision=6, scale=3), server_default="0", nullable=False
        ),
        sa.Column("grn_qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("po_rate", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["grn_line_id"],
            ["grn_lines.id"],
            name=op.f("fk_vendor_bill_lines_grn_line_id_grn_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["po_line_id"],
            ["po_lines.id"],
            name=op.f("fk_vendor_bill_lines_po_line_id_po_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_bill_id"],
            ["vendor_bills.id"],
            name=op.f("fk_vendor_bill_lines_vendor_bill_id_vendor_bills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bill_lines")),
    )
    op.create_index(
        op.f("ix_vendor_bill_lines_vendor_bill_id"),
        "vendor_bill_lines",
        ["vendor_bill_id"],
        unique=False,
    )
    op.add_column("site_issues", sa.Column("subcontractor_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_site_issues_subcontractor_id"), "site_issues", ["subcontractor_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_site_issues_subcontractor_id_vendors"),
        "site_issues",
        "vendors",
        ["subcontractor_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_site_issues_subcontractor_id_vendors"), "site_issues", type_="foreignkey"
    )
    op.drop_index(op.f("ix_site_issues_subcontractor_id"), table_name="site_issues")
    op.drop_column("site_issues", "subcontractor_id")
    op.drop_index(op.f("ix_vendor_bill_lines_vendor_bill_id"), table_name="vendor_bill_lines")
    op.drop_table("vendor_bill_lines")
    op.drop_index(op.f("ix_subcon_bill_lines_subcon_bill_id"), table_name="subcon_bill_lines")
    op.drop_table("subcon_bill_lines")
    op.drop_table("vendor_bill_grns")
    op.drop_index(op.f("ix_receipt_allocations_receipt_id"), table_name="receipt_allocations")
    op.drop_index(op.f("ix_receipt_allocations_invoice_id"), table_name="receipt_allocations")
    op.drop_table("receipt_allocations")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_tax_invoices_site_id"), table_name="tax_invoices")
    op.drop_index(op.f("ix_tax_invoices_invoice_date"), table_name="tax_invoices")
    op.drop_index(op.f("ix_tax_invoices_client_id"), table_name="tax_invoices")
    op.drop_table("tax_invoices")
    op.drop_index(op.f("ix_ra_bill_lines_ra_bill_id"), table_name="ra_bill_lines")
    op.drop_table("ra_bill_lines")
    op.drop_index(op.f("ix_labour_advances_site_id"), table_name="labour_advances")
    op.drop_index(op.f("ix_labour_advances_labour_id"), table_name="labour_advances")
    op.drop_table("labour_advances")
    op.drop_index(
        op.f("ix_subcon_retention_releases_wo_id"), table_name="subcon_retention_releases"
    )
    op.drop_table("subcon_retention_releases")
    op.drop_index(op.f("ix_subcon_bills_wo_id"), table_name="subcon_bills")
    op.drop_table("subcon_bills")
    op.drop_index(op.f("ix_ra_bills_status"), table_name="ra_bills")
    op.drop_index(op.f("ix_ra_bills_site_id"), table_name="ra_bills")
    op.drop_index(op.f("ix_ra_bills_contract_id"), table_name="ra_bills")
    op.drop_table("ra_bills")
    op.drop_index(op.f("ix_payment_allocations_vendor_bill_id"), table_name="payment_allocations")
    op.drop_index(op.f("ix_payment_allocations_payment_id"), table_name="payment_allocations")
    op.drop_table("payment_allocations")
    op.drop_index(op.f("ix_labour_wage_payments_site_id"), table_name="labour_wage_payments")
    op.drop_index(op.f("ix_labour_wage_payments_labour_id"), table_name="labour_wage_payments")
    op.drop_table("labour_wage_payments")
    op.drop_index(op.f("ix_contract_lines_contract_id"), table_name="contract_lines")
    op.drop_table("contract_lines")
    op.drop_index(op.f("ix_vendor_bills_vendor_id"), table_name="vendor_bills")
    op.drop_index(op.f("ix_vendor_bills_status"), table_name="vendor_bills")
    op.drop_index(op.f("ix_vendor_bills_site_id"), table_name="vendor_bills")
    op.drop_index(op.f("ix_vendor_bills_due_date"), table_name="vendor_bills")
    op.drop_table("vendor_bills")
    op.drop_index(op.f("ix_retention_releases_site_id"), table_name="retention_releases")
    op.drop_table("retention_releases")
    op.drop_index(op.f("ix_receipts_on_date"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_client_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_petty_cash_entries_site_id"), table_name="petty_cash_entries")
    op.drop_index(op.f("ix_petty_cash_entries_on_date"), table_name="petty_cash_entries")
    op.drop_index(op.f("ix_petty_cash_entries_account_id"), table_name="petty_cash_entries")
    op.drop_table("petty_cash_entries")
    op.drop_table("client_contracts")
    op.drop_index(op.f("ix_staff_advances_user_id"), table_name="staff_advances")
    op.drop_table("staff_advances")
    op.drop_index(op.f("ix_payslips_run_id"), table_name="payslips")
    op.drop_table("payslips")
    op.drop_index(op.f("ix_payments_vendor_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_on_date"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("tally_exports")
    op.drop_index(op.f("ix_salary_structures_user_id"), table_name="salary_structures")
    op.drop_table("salary_structures")
    op.drop_table("petty_cash_accounts")
    op.drop_table("payroll_runs")
    op.drop_table("finance_settings")
    op.drop_table("expense_categories")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("billing.view", "finance", "View client contracts, RA bills, invoices and receipts"),
    ("billing.edit", "finance", "Make RA bills, invoices and receipts"),
    ("billing.approve", "finance", "Approve extra items beyond the BOQ, credit notes"),
    ("payables.view", "finance", "View vendor and subcontractor bills and payments"),
    ("payables.edit", "finance", "Enter vendor bills, subcontractor bills and payments"),
    ("payables.approve", "finance", "Approve payments above the limit"),
    ("expense.create", "finance", "Spend petty cash and claim expenses"),
    ("expense.approve", "finance", "Approve expenses, give petty cash advances"),
    ("payroll.view", "finance", "See salaries, payslips and payroll"),
    ("payroll.edit", "finance", "Set salaries, run payroll"),
    ("finance.export", "finance", "Export vouchers to Tally"),
]
CODES = [c for c, _, _ in NEW_PERMISSIONS]
NOT_PAYROLL = [c for c in CODES if not c.startswith("payroll.")]
GRANTS = {
    "super_admin": dict.fromkeys(CODES, "all"),
    # approvals, but no salaries
    "office_admin": dict.fromkeys(NOT_PAYROLL, "all"),
    # everything except the approvals above limits
    "accounts": dict.fromkeys(
        [
            "billing.view",
            "billing.edit",
            "payables.view",
            "payables.edit",
            "expense.create",
            "expense.approve",
            "payroll.view",
            "payroll.edit",
            "finance.export",
        ],
        "all",
    ),
    "site_supervisor": {"expense.create": "own"},
    "sales": {"billing.view": "assigned"},
}
# the M0 placeholder the expense codes replace
OLD = ("pettycash.manage", "pettycash", "Manage petty cash")
OLD_GRANTS = [
    ("office_admin", "all"),
    ("accounts", "all"),
    ("site_supervisor", "assigned"),
    ("super_admin", "all"),
]

TDS_RULES = {
    "material_supplier": {"section": "194Q", "individual": 0.1, "other": 0.1},
    "subcontractor": {"section": "194C", "individual": 1, "other": 2},
    "labour_contractor": {"section": "194C", "individual": 1, "other": 2},
    "transporter": {"section": "194C", "individual": 1, "other": 2},
    "other": {"section": "194J", "individual": 10, "other": 10},
}
PT_GUJARAT = [{"from": 0, "to": 11999, "amount": 0}, {"from": 12000, "to": None, "amount": 200}]
LEDGERS = {
    "sales": "Works Contract Sales",
    "purchase": "Purchase - Material",
    "subcontract": "Subcontract Charges",
    "service": "Service Charges",
    "freight": "Freight Inward",
    "output_cgst": "Output CGST",
    "output_sgst": "Output SGST",
    "output_igst": "Output IGST",
    "input_cgst": "Input CGST",
    "input_sgst": "Input SGST",
    "input_igst": "Input IGST",
    "tds_payable": "TDS Payable",
    "tds_receivable": "TDS Receivable",
    "gst_tds_receivable": "GST TDS Receivable",
    "retention_payable": "Retention Payable",
    "client_advance": "Client Advances",
    "round_off": "Round Off",
    "cash": "Cash",
    "bank_default": "Bank",
    "write_off": "Discount Allowed",
    "site_expenses": "Site Expenses",
    "petty_cash_prefix": "Petty Cash - ",
    "salary": "Salaries",
    "salary_payable": "Salary Payable",
    "pf_payable": "PF Payable",
    "esi_payable": "ESI Payable",
    "pt_payable": "Professional Tax Payable",
    "staff_advance": "Staff Advances",
    "labour_wages": "Labour Wages",
    "banks": {},
}
CATEGORIES = [
    ("Food", "other"),
    ("Travel", "other"),
    ("Local purchase", "material"),
    ("Labour advance", "labour"),
    ("Transport", "freight"),
    ("Site misc", "other"),
]


def _grant(role: str, code: str, scope: str) -> None:
    op.execute(
        "INSERT INTO role_permissions (role_id, permission_code, scope) "
        f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
        f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
    )


def _seed() -> None:
    import json

    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            _grant(role, code, scope)
    op.execute(f"DELETE FROM permissions WHERE code = '{OLD[0]}'")
    op.execute(
        "INSERT INTO finance_settings (id, tds_rules, pt_slabs, tally_ledgers) VALUES (1, "
        f"'{json.dumps(TDS_RULES)}', '{json.dumps(PT_GUJARAT)}', '{json.dumps(LEDGERS)}')"
    )
    for name, head in CATEGORIES:
        op.execute(
            f"INSERT INTO expense_categories (name, budget_head) VALUES ('{name}', '{head}')"
        )


def _unseed() -> None:
    op.execute(
        "INSERT INTO permissions (code, module, description) VALUES "
        f"('{OLD[0]}', '{OLD[1]}', '{OLD[2]}') ON CONFLICT DO NOTHING"
    )
    for role, scope in OLD_GRANTS:
        _grant(role, OLD[0], scope)
    op.execute("DELETE FROM permissions WHERE code IN (" + ", ".join(f"'{c}'" for c in CODES) + ")")
