"""M5 review fixes: TDS thresholds (194Q only when it applies, above its threshold), invoice GST
rounded per line, payslip net rounded to the rupee, payroll identifiers on users.

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-07 14:34:21.009909

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "finance_settings",
        sa.Column("tds_194q_applies", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "finance_settings",
        sa.Column(
            "tds_thresholds",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=(
                '{"194Q": {"annual": 5000000}, "194C": {"single": 30000, "annual": 100000}, '
                '"194J": {"annual": 50000}}'
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "payslips",
        sa.Column(
            "round_off", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
    )
    op.add_column("users", sa.Column("pan", sa.String(length=10), nullable=True))
    op.add_column("users", sa.Column("uan", sa.String(length=12), nullable=True))
    op.add_column("users", sa.Column("esi_no", sa.String(length=17), nullable=True))
    op.add_column("users", sa.Column("bank_account", sa.String(length=34), nullable=True))
    op.add_column("users", sa.Column("bank_ifsc", sa.String(length=11), nullable=True))
    # ### end Alembic commands ###
    _data()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bank_ifsc")
    op.drop_column("users", "bank_account")
    op.drop_column("users", "esi_no")
    op.drop_column("users", "uan")
    op.drop_column("users", "pan")
    op.drop_column("payslips", "round_off")
    op.drop_column("finance_settings", "tds_thresholds")
    op.drop_column("finance_settings", "tds_194q_applies")
    # ### end Alembic commands ###


def _data() -> None:
    from decimal import ROUND_HALF_UP, Decimal

    bind = op.get_bind()
    # 194Q is off by default now: bills that deducted it pay the full amount
    bind.execute(
        sa.text(
            "UPDATE vendor_bills SET payable = payable + tds_amount, tds_amount = 0, "
            "tds_percent = 0 "
            "WHERE tds_section = '194Q' AND kind <> 'subcontract' AND tds_amount > 0"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE vendor_bills b SET status = CASE WHEN p.paid >= b.payable THEN 'paid' "
            "WHEN p.paid > 0 THEN 'partly_paid' ELSE 'approved' END "
            "FROM (SELECT a.vendor_bill_id, sum(a.amount) AS paid FROM payment_allocations a "
            "JOIN payments y ON y.id = a.payment_id AND y.status = 'paid' "
            "GROUP BY a.vendor_bill_id) p "
            "WHERE p.vendor_bill_id = b.id AND b.status NOT IN ('draft', 'cancelled')"
        )
    )
    # invoice GST: the totals are the sums of the per-line amounts (each rounded to paise)
    cent = Decimal("0.01")
    for inv_id, interstate in bind.execute(
        sa.text("SELECT id, interstate FROM tax_invoices")
    ).all():
        taxable = cgst = sgst = igst = Decimal(0)
        for amount, rate in bind.execute(
            sa.text("SELECT amount, gst_percent FROM invoice_lines WHERE invoice_id = :i"),
            {"i": inv_id},
        ).all():
            taxable += amount
            if interstate:
                igst += (amount * rate / 100).quantize(cent, ROUND_HALF_UP)
            else:
                half = (amount * rate / 200).quantize(cent, ROUND_HALF_UP)
                cgst, sgst = cgst + half, sgst + half
        before = taxable + cgst + sgst + igst
        total = before.quantize(Decimal(1), ROUND_HALF_UP)
        bind.execute(
            sa.text(
                "UPDATE tax_invoices SET taxable = :t, cgst = :c, sgst = :s, igst = :g, "
                "total = :tot, "
                "round_off = :r WHERE id = :i"
            ),
            {
                "t": taxable,
                "c": cgst,
                "s": sgst,
                "g": igst,
                "tot": total,
                "r": total - before,
                "i": inv_id,
            },
        )
    # payslips: net pay to the rupee
    exact = "(gross - pf_employee - esi_employee - pt - advance_recovery)"
    bind.execute(
        sa.text(f"UPDATE payslips SET net = round({exact}), round_off = round({exact}) - {exact}")
    )
