"""M6: client portal - client users, invites, per-site portal settings, shared documents, snags,
comments, notifications and their outbox; share-with-client flags, inspection client sign-off,
MOM acknowledgement, client RA bill certification; portal permissions.

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-08 06:06:01.932004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portal_invites",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_portal_invites_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_portal_invites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portal_invites")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_portal_invites_token_hash")),
    )
    op.create_index(op.f("ix_portal_invites_user_id"), "portal_invites", ["user_id"], unique=False)
    op.create_table(
        "client_users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_users_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_client_users_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "client_id", name=op.f("pk_client_users")),
    )
    op.create_index(op.f("ix_client_users_client_id"), "client_users", ["client_id"], unique=False)
    op.create_table(
        "client_user_sites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_client_user_sites_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_client_user_sites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "site_id", name=op.f("pk_client_user_sites")),
    )
    op.create_index(
        op.f("ix_client_user_sites_site_id"), "client_user_sites", ["site_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=12), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("internal", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("author_side", sa.String(length=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('dpr', 'inspection', 'snag', 'ra_bill')",
            name=op.f("ck_comments_entity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_comments_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index("ix_comments_entity", "comments", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_comments_site_id"), "comments", ["site_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_notifications_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "site_documents",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="document", nullable=False),
        sa.Column("source", sa.String(length=6), server_default="staff", nullable=False),
        sa.Column("stored_path", sa.String(length=400), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("share_with_client", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "source IN ('staff', 'client')", name=op.f("ck_site_documents_source_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_site_documents_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_documents_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_documents")),
    )
    op.create_index(op.f("ix_site_documents_site_id"), "site_documents", ["site_id"], unique=False)
    op.create_table(
        "site_portal",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("visible", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "sections", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_site_portal_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_site_portal_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("site_id", name=op.f("pk_site_portal")),
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=10), server_default="in_app", nullable=False),
        sa.Column("status", sa.String(length=8), server_default="sent", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "channel IN ('in_app', 'email', 'sms', 'whatsapp')",
            name=op.f("ck_notification_outbox_channel_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'sent', 'failed')",
            name=op.f("ck_notification_outbox_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_outbox_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_outbox")),
    )
    op.create_index(
        op.f("ix_notification_outbox_notification_id"),
        "notification_outbox",
        ["notification_id"],
        unique=False,
    )
    op.create_table(
        "snags",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("area", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("raised_by_side", sa.String(length=6), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="open", nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("fixed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reopened", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "raised_by_side IN ('client', 'staff')", name=op.f("ck_snags_side_valid")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'fixed', 'verified', 'closed')",
            name=op.f("ck_snags_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_snags_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_snags_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["site_nodes.id"],
            name=op.f("fk_snags_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_snags_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snags")),
        sa.UniqueConstraint("code", name=op.f("uq_snags_code")),
    )
    op.create_index(op.f("ix_snags_site_id"), "snags", ["site_id"], unique=False)
    op.create_index(op.f("ix_snags_status"), "snags", ["status"], unique=False)
    op.create_table(
        "snag_photos",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("snag_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=6), server_default="before", nullable=False),
        sa.Column("stored_path", sa.String(length=400), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("kind IN ('before', 'after')", name=op.f("ck_snag_photos_kind_valid")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_snag_photos_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["snag_id"], ["snags.id"], name=op.f("fk_snag_photos_snag_id_snags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_snag_photos")),
    )
    op.create_index(op.f("ix_snag_photos_snag_id"), "snag_photos", ["snag_id"], unique=False)
    op.add_column(
        "company_profile",
        sa.Column("portal_invite_days", sa.Integer(), server_default="7", nullable=False),
    )
    op.add_column(
        "drawings",
        sa.Column("share_with_client", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "inspections",
        sa.Column("client_signoff", sa.String(length=8), server_default="none", nullable=False),
    )
    op.add_column(
        "inspections", sa.Column("client_signed_name", sa.String(length=200), nullable=True)
    )
    op.add_column("inspections", sa.Column("client_signed_by", sa.UUID(), nullable=True))
    op.add_column(
        "inspections", sa.Column("client_signed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "inspections", sa.Column("client_signature_path", sa.String(length=400), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_inspections_client_signed_by_users"),
        "inspections",
        "users",
        ["client_signed_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "mom_points", sa.Column("client_acknowledged_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("mom_points", sa.Column("client_acknowledged_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_mom_points_client_acknowledged_by_users"),
        "mom_points",
        "users",
        ["client_acknowledged_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "ra_bill_lines", sa.Column("client_qty", sa.Numeric(precision=14, scale=3), nullable=True)
    )
    op.add_column("ra_bills", sa.Column("client_remark", sa.Text(), nullable=True))
    op.add_column("ra_bills", sa.Column("client_acted_by", sa.UUID(), nullable=True))
    op.add_column(
        "ra_bills", sa.Column("client_acted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_ra_bills_client_acted_by_users"),
        "ra_bills",
        "users",
        ["client_acted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "task_photos",
        sa.Column("share_with_client", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_photos", "share_with_client")
    op.drop_constraint(op.f("fk_ra_bills_client_acted_by_users"), "ra_bills", type_="foreignkey")
    op.drop_column("ra_bills", "client_acted_at")
    op.drop_column("ra_bills", "client_acted_by")
    op.drop_column("ra_bills", "client_remark")
    op.drop_column("ra_bill_lines", "client_qty")
    op.drop_constraint(
        op.f("fk_mom_points_client_acknowledged_by_users"), "mom_points", type_="foreignkey"
    )
    op.drop_column("mom_points", "client_acknowledged_by")
    op.drop_column("mom_points", "client_acknowledged_at")
    op.drop_constraint(
        op.f("fk_inspections_client_signed_by_users"), "inspections", type_="foreignkey"
    )
    op.drop_column("inspections", "client_signature_path")
    op.drop_column("inspections", "client_signed_at")
    op.drop_column("inspections", "client_signed_by")
    op.drop_column("inspections", "client_signed_name")
    op.drop_column("inspections", "client_signoff")
    op.drop_column("drawings", "share_with_client")
    op.drop_column("company_profile", "portal_invite_days")
    op.drop_index(op.f("ix_snag_photos_snag_id"), table_name="snag_photos")
    op.drop_table("snag_photos")
    op.drop_index(op.f("ix_snags_status"), table_name="snags")
    op.drop_index(op.f("ix_snags_site_id"), table_name="snags")
    op.drop_table("snags")
    op.drop_index(op.f("ix_notification_outbox_notification_id"), table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_table("site_portal")
    op.drop_index(op.f("ix_site_documents_site_id"), table_name="site_documents")
    op.drop_table("site_documents")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_comments_site_id"), table_name="comments")
    op.drop_index("ix_comments_entity", table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_client_user_sites_site_id"), table_name="client_user_sites")
    op.drop_table("client_user_sites")
    op.drop_index(op.f("ix_client_users_client_id"), table_name="client_users")
    op.drop_table("client_users")
    op.drop_index(op.f("ix_portal_invites_user_id"), table_name="portal_invites")
    op.drop_table("portal_invites")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("portal.view", "portal", "Client portal: see their own sites"),
    ("portal.comment", "portal", "Client portal: comment, upload their drawings"),
    ("portal.snag", "portal", "Client portal: raise and verify snags"),
    (
        "portal.approve",
        "portal",
        "Client portal: certify RA bills, sign inspections, acknowledge MOM",
    ),
    ("portal.manage", "portal", "Invite client users and choose what each site shows"),
]
CLIENT = ["portal.view", "portal.comment", "portal.snag", "portal.approve"]
GRANTS = {
    "client": dict.fromkeys(CLIENT, "own"),
    "super_admin": dict.fromkeys([c for c, _, _ in NEW_PERMISSIONS], "all"),
    "office_admin": {"portal.manage": "all"},
    "sales": {"portal.manage": "assigned"},
}
RA_OLD = "'draft', 'submitted', 'certified', 'invoiced', 'cancelled'"
RA_NEW = (
    "'draft', 'submitted', 'certified_by_client', 'rejected_by_client', 'certified', 'invoiced', "
    "'cancelled'"
)


def _ra_statuses(values: str) -> None:
    op.drop_constraint(op.f("ck_ra_bills_status_valid"), "ra_bills", type_="check")
    op.create_check_constraint("status_valid", "ra_bills", f"status IN ({values})")


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            op.execute(
                "INSERT INTO role_permissions (role_id, permission_code, scope) "
                f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
                f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
            )
    op.alter_column("ra_bills", "status", type_=sa.String(20), existing_type=sa.String(10))
    _ra_statuses(RA_NEW)
    op.create_check_constraint(
        "signoff_valid", "inspections", "client_signoff IN ('none', 'waiting', 'signed')"
    )


def _unseed() -> None:
    op.execute("UPDATE ra_bills SET status = 'submitted' WHERE status LIKE '%by_client'")
    _ra_statuses(RA_OLD)
    op.alter_column("ra_bills", "status", type_=sa.String(10), existing_type=sa.String(20))
    op.execute(
        "DELETE FROM permissions WHERE code IN ("
        + ", ".join(f"'{c}'" for c, _, _ in NEW_PERMISSIONS)
        + ")"
    )
