"""M7: dashboards and analytics - summary tables, progress snapshots, KPI snapshots, alerts,
weekly reports, demo-row registry; lost reasons on tenders and leads, tender decided_at, product
reorder level, demo flags, dashboard indexes; dashboard and report permissions.

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-08 08:42:18.352643

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo_rows",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("table_name", sa.String(length=60), nullable=False),
        sa.Column("row_key", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_rows")),
    )
    op.create_table(
        "kpi_snapshots",
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("on_date", "is_demo", name=op.f("pk_kpi_snapshots")),
    )
    op.create_table(
        "weekly_reports",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weekly_reports")),
        sa.UniqueConstraint("week_start", name=op.f("uq_weekly_reports_week_start")),
    )
    op.create_table(
        "analytics_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "delay_threshold_points",
            sa.Numeric(precision=7, scale=2),
            server_default="15",
            nullable=False,
        ),
        sa.Column("ack_snooze_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column(
            "alert_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("weekly_report", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alerts_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_analytics_settings_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_settings")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("rule", sa.String(length=20), nullable=False),
        sa.Column("item_key", sa.String(length=60), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=True),
        sa.Column("severity", sa.String(length=8), server_default="warn", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "rule IN ('dpr_missing', 'behind_schedule', 'budget_head', 'invoice_overdue', "
            "'po_late', 'low_stock', 'petty_negative', 'tender_due', 'kylas_failing')",
            name=op.f("ck_alerts_rule_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("fk_alerts_acknowledged_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_alerts_site_id_sites"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("rule", "item_key", "day", name=op.f("uq_alerts_rule")),
    )
    op.create_index(op.f("ix_alerts_day"), "alerts", ["day"], unique=False)
    op.create_index(op.f("ix_alerts_rule"), "alerts", ["rule"], unique=False)
    op.create_table(
        "monthly_summaries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("billed", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False),
        sa.Column(
            "invoiced", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "credited", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "received", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column("settled", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False),
        sa.Column("cost", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False),
        sa.Column(
            "salary_cost", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "man_days", sa.Numeric(precision=12, scale=1), server_default="0", nullable=False
        ),
        sa.Column(
            "labour_cost", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column("marked", sa.Integer(), server_default="0", nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_monthly_summaries_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monthly_summaries")),
        sa.UniqueConstraint(
            "month",
            "site_id",
            "is_demo",
            name=op.f("uq_monthly_summaries_month"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_monthly_summaries_month"), "monthly_summaries", ["month"], unique=False
    )
    op.create_table(
        "progress_snapshots",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("on_date", sa.Date(), nullable=False),
        sa.Column("percent", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_progress_snapshots_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("site_id", "on_date", name=op.f("pk_progress_snapshots")),
    )
    op.create_table(
        "site_summaries",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("historic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("client_type", sa.String(length=20), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("salesperson_id", sa.Uuid(), nullable=True),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("progress", sa.Numeric(precision=7, scale=2), server_default="0", nullable=False),
        sa.Column("elapsed", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("rate_per_day", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("forecast_end", sa.Date(), nullable=True),
        sa.Column("delayed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("delay_reason", sa.String(length=40), nullable=True),
        sa.Column("contract_value", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("billed", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False),
        sa.Column(
            "certified", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "received", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "outstanding", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "retention_held", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column("cost", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False),
        sa.Column(
            "cost_heads",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "salary_cost", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "budget_heads",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("tender_margin", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("open_snags", sa.Integer(), server_default="0", nullable=False),
        sa.Column("closed_snags", sa.Integer(), server_default="0", nullable=False),
        sa.Column("snag_close_days", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column(
            "man_days", sa.Numeric(precision=12, scale=1), server_default="0", nullable=False
        ),
        sa.Column(
            "labour_cost", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "area_done", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "material_value", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False
        ),
        sa.Column("freight", sa.Numeric(precision=16, scale=2), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_site_summaries_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("site_id", name=op.f("pk_site_summaries")),
    )
    op.create_index(op.f("ix_site_summaries_is_demo"), "site_summaries", ["is_demo"], unique=False)
    op.create_table(
        "alert_recipients",
        sa.Column("alert_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_alert_recipients_alert_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_alert_recipients_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("alert_id", "user_id", name=op.f("pk_alert_recipients")),
    )
    op.create_index(
        op.f("ix_alert_recipients_user_id"), "alert_recipients", ["user_id"], unique=False
    )
    op.create_table(
        "invoice_summaries",
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("total", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("outstanding", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("retention_held", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("due", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["tax_invoices.id"],
            name=op.f("fk_invoice_summaries_invoice_id_tax_invoices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("invoice_id", name=op.f("pk_invoice_summaries")),
    )
    op.create_index(
        op.f("ix_invoice_summaries_client_id"), "invoice_summaries", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_summaries_is_demo"), "invoice_summaries", ["is_demo"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_summaries_site_id"), "invoice_summaries", ["site_id"], unique=False
    )
    op.create_index("ix_attendance_site_date", "attendance", ["site_id", "on_date"], unique=False)
    op.add_column(
        "clients",
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(op.f("ix_clients_is_demo"), "clients", ["is_demo"], unique=False)
    op.create_index(
        "ix_equipment_usage_site_date", "equipment_usage", ["site_id", "on_date"], unique=False
    )
    op.create_index(
        "ix_freight_entries_site_date", "freight_entries", ["site_id", "on_date"], unique=False
    )
    op.add_column("leads", sa.Column("lost_reason", sa.String(length=12), nullable=True))
    op.add_column("leads", sa.Column("lost_to", sa.String(length=200), nullable=True))
    op.add_column("leads", sa.Column("lost_note", sa.Text(), nullable=True))
    op.add_column(
        "leads", sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.create_index("ix_leads_created_at", "leads", ["created_at"], unique=False)
    op.create_index(op.f("ix_leads_is_demo"), "leads", ["is_demo"], unique=False)
    op.create_index("ix_leads_owner_status", "leads", ["owner_id", "status"], unique=False)
    op.create_index(
        "ix_payment_allocations_bill", "payment_allocations", ["vendor_bill_id"], unique=False
    )
    op.create_index("ix_po_lines_product", "po_lines", ["product_id"], unique=False)
    op.add_column(
        "products",
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "products", sa.Column("reorder_level", sa.Numeric(precision=14, scale=3), nullable=True)
    )
    op.create_index(op.f("ix_products_is_demo"), "products", ["is_demo"], unique=False)
    op.create_index("ix_purchase_orders_po_date", "purchase_orders", ["po_date"], unique=False)
    op.create_index(
        "ix_purchase_orders_status_delivery",
        "purchase_orders",
        ["status", "expected_delivery"],
        unique=False,
    )
    op.create_index("ix_ra_bills_site_status", "ra_bills", ["site_id", "status"], unique=False)
    op.create_index("ix_receipts_site_id", "receipts", ["site_id"], unique=False)
    op.create_index("ix_site_costs_site_date", "site_costs", ["site_id", "on_date"], unique=False)
    op.create_index(
        "ix_site_issues_site_date", "site_issues", ["site_id", "issued_on"], unique=False
    )
    op.add_column(
        "sites", sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.create_index(op.f("ix_sites_is_demo"), "sites", ["is_demo"], unique=False)
    op.create_index("ix_stock_ledger_product", "stock_ledger", ["product_id"], unique=False)
    op.create_index("ix_tasks_site_status", "tasks", ["site_id", "status"], unique=False)
    op.create_index("ix_tax_invoices_against_id", "tax_invoices", ["against_id"], unique=False)
    op.add_column("tenders", sa.Column("lost_note", sa.Text(), nullable=True))
    op.add_column("tenders", sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "tenders",
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index("ix_tenders_decided_at", "tenders", ["decided_at"], unique=False)
    op.create_index(op.f("ix_tenders_is_demo"), "tenders", ["is_demo"], unique=False)
    op.create_index("ix_tenders_owner", "tenders", ["owner_id"], unique=False)
    op.create_index("ix_tenders_status_due", "tenders", ["status", "due_on"], unique=False)
    op.add_column(
        "users", sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.create_index(op.f("ix_users_is_demo"), "users", ["is_demo"], unique=False)
    op.create_index(
        "ix_vendor_bills_status_due", "vendor_bills", ["status", "due_date"], unique=False
    )
    op.add_column(
        "vendors",
        sa.Column("is_demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(op.f("ix_vendors_is_demo"), "vendors", ["is_demo"], unique=False)
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendors_is_demo"), table_name="vendors")
    op.drop_column("vendors", "is_demo")
    op.drop_index("ix_vendor_bills_status_due", table_name="vendor_bills")
    op.drop_index(op.f("ix_users_is_demo"), table_name="users")
    op.drop_column("users", "is_demo")
    op.drop_index("ix_tenders_status_due", table_name="tenders")
    op.drop_index("ix_tenders_owner", table_name="tenders")
    op.drop_index(op.f("ix_tenders_is_demo"), table_name="tenders")
    op.drop_index("ix_tenders_decided_at", table_name="tenders")
    op.drop_column("tenders", "is_demo")
    op.drop_column("tenders", "decided_at")
    op.drop_column("tenders", "lost_note")
    op.drop_index("ix_tax_invoices_against_id", table_name="tax_invoices")
    op.drop_index("ix_tasks_site_status", table_name="tasks")
    op.drop_index("ix_stock_ledger_product", table_name="stock_ledger")
    op.drop_index(op.f("ix_sites_is_demo"), table_name="sites")
    op.drop_column("sites", "is_demo")
    op.drop_index("ix_site_issues_site_date", table_name="site_issues")
    op.drop_index("ix_site_costs_site_date", table_name="site_costs")
    op.drop_index("ix_receipts_site_id", table_name="receipts")
    op.drop_index("ix_ra_bills_site_status", table_name="ra_bills")
    op.drop_index("ix_purchase_orders_status_delivery", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_po_date", table_name="purchase_orders")
    op.drop_index(op.f("ix_products_is_demo"), table_name="products")
    op.drop_column("products", "reorder_level")
    op.drop_column("products", "is_demo")
    op.drop_index("ix_po_lines_product", table_name="po_lines")
    op.drop_index("ix_payment_allocations_bill", table_name="payment_allocations")
    op.drop_index("ix_leads_owner_status", table_name="leads")
    op.drop_index(op.f("ix_leads_is_demo"), table_name="leads")
    op.drop_index("ix_leads_created_at", table_name="leads")
    op.drop_column("leads", "is_demo")
    op.drop_column("leads", "lost_note")
    op.drop_column("leads", "lost_to")
    op.drop_column("leads", "lost_reason")
    op.drop_index("ix_freight_entries_site_date", table_name="freight_entries")
    op.drop_index("ix_equipment_usage_site_date", table_name="equipment_usage")
    op.drop_index(op.f("ix_clients_is_demo"), table_name="clients")
    op.drop_column("clients", "is_demo")
    op.drop_index("ix_attendance_site_date", table_name="attendance")
    op.drop_index(op.f("ix_invoice_summaries_site_id"), table_name="invoice_summaries")
    op.drop_index(op.f("ix_invoice_summaries_is_demo"), table_name="invoice_summaries")
    op.drop_index(op.f("ix_invoice_summaries_client_id"), table_name="invoice_summaries")
    op.drop_table("invoice_summaries")
    op.drop_index(op.f("ix_alert_recipients_user_id"), table_name="alert_recipients")
    op.drop_table("alert_recipients")
    op.drop_index(op.f("ix_site_summaries_is_demo"), table_name="site_summaries")
    op.drop_table("site_summaries")
    op.drop_table("progress_snapshots")
    op.drop_index(op.f("ix_monthly_summaries_month"), table_name="monthly_summaries")
    op.drop_table("monthly_summaries")
    op.drop_index(op.f("ix_alerts_rule"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_day"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_table("analytics_settings")
    op.drop_table("weekly_reports")
    op.drop_table("kpi_snapshots")
    op.drop_table("demo_rows")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("dashboard.company", "dashboard", "Management dashboard: the whole company"),
    ("dashboard.sales", "dashboard", "Sales dashboard and strategy analytics"),
    ("dashboard.site", "dashboard", "Site supervisor dashboard"),
    ("dashboard.finance", "dashboard", "Accounts dashboard and finance analytics"),
    ("dashboard.purchase", "dashboard", "Store / purchase dashboard and purchase analytics"),
    ("reports.export", "dashboard", "Excel and PDF exports of dashboards and reports"),
]
GRANTS = {
    "super_admin": dict.fromkeys([c for c, _, _ in NEW_PERMISSIONS], "all"),
    "office_admin": {"dashboard.company": "all", "dashboard.sales": "all", "reports.export": "all"},
    "sales": {"dashboard.sales": "own"},
    "site_supervisor": {"dashboard.site": "assigned"},
    "accounts": {"dashboard.finance": "all", "reports.export": "all"},
    "store_purchase": {"dashboard.purchase": "all"},
}
LOST = "'price', 'competitor', 'timing', 'spec', 'relationship', 'other'"


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            op.execute(
                "INSERT INTO role_permissions (role_id, permission_code, scope) "
                f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
                f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
            )
    op.execute("INSERT INTO analytics_settings (id) VALUES (1)")
    # free-text lost reasons become 'other', the text kept as the note
    op.execute(
        "UPDATE tenders SET lost_note = lost_reason, lost_reason = 'other' "
        f"WHERE lost_reason IS NOT NULL AND lost_reason NOT IN ({LOST})"
    )
    op.execute(
        "UPDATE tenders SET decided_at = updated_at WHERE status IN ('won', 'lost', 'dropped')"
    )
    op.create_check_constraint(
        "lost_reason_valid", "tenders", f"lost_reason IS NULL OR lost_reason IN ({LOST})"
    )
    op.create_check_constraint(
        "lost_reason_valid", "leads", f"lost_reason IS NULL OR lost_reason IN ({LOST})"
    )


def _unseed() -> None:
    op.drop_constraint(op.f("ck_leads_lost_reason_valid"), "leads", type_="check")
    op.drop_constraint(op.f("ck_tenders_lost_reason_valid"), "tenders", type_="check")
    op.execute(
        "UPDATE tenders SET lost_reason = lost_note WHERE lost_reason = 'other' "
        "AND lost_note IS NOT NULL"
    )
    op.execute(
        "DELETE FROM permissions WHERE code IN ("
        + ", ".join(f"'{c}'" for c, _, _ in NEW_PERMISSIONS)
        + ")"
    )
