"""M6b: site survey - area types, surveys and their areas and photos, BOQ links, survey settings,
AI call log; product pack unit, user measuring unit; survey permissions.

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-08 12:50:18.980151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("photo_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("camera_billing_allowed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "mismatch_percent", sa.Numeric(precision=6, scale=2), server_default="3", nullable=False
        ),
        sa.Column("ai_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "ai_model", sa.String(length=60), server_default="claude-sonnet-5-5", nullable=False
        ),
        sa.Column(
            "ai_monthly_cap_inr",
            sa.Numeric(precision=10, scale=2),
            server_default="2000",
            nullable=False,
        ),
        sa.Column(
            "ai_usd_per_mtok_in",
            sa.Numeric(precision=8, scale=3),
            server_default="3",
            nullable=False,
        ),
        sa.Column(
            "ai_usd_per_mtok_out",
            sa.Numeric(precision=8, scale=3),
            server_default="15",
            nullable=False,
        ),
        sa.Column(
            "ai_inr_per_usd", sa.Numeric(precision=8, scale=2), server_default="85", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_survey_settings_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_settings")),
    )
    op.create_table(
        "area_types",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("default_system_id", sa.Integer(), nullable=True),
        sa.Column(
            "default_upturn_mm",
            sa.Numeric(precision=7, scale=1),
            server_default="0",
            nullable=False,
        ),
        sa.Column("default_wastage_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("includes_walls", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("needs_sunk_depth", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_area_types_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["default_system_id"],
            ["systems.id"],
            name=op.f("fk_area_types_default_system_id_systems"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_area_types")),
        sa.UniqueConstraint("name", name=op.f("uq_area_types_name")),
    )
    op.create_table(
        "surveys",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("tender_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("surveyed_on", sa.Date(), nullable=True),
        sa.Column("surveyed_by", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="draft", nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'approved')", name=op.f("ck_surveys_status_valid")
        ),
        sa.CheckConstraint(
            "(lead_id IS NOT NULL)::int + (tender_id IS NOT NULL)::int "
            "+ (site_id IS NOT NULL)::int = 1",
            name=op.f("ck_surveys_one_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_surveys_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_surveys_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_surveys_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_surveys_site_id_sites"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["surveyed_by"],
            ["users.id"],
            name=op.f("fk_surveys_surveyed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
            name=op.f("fk_surveys_tender_id_tenders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surveys")),
        sa.UniqueConstraint("code", name=op.f("uq_surveys_code")),
    )
    op.create_index(op.f("ix_surveys_lead_id"), "surveys", ["lead_id"], unique=False)
    op.create_index(op.f("ix_surveys_site_id"), "surveys", ["site_id"], unique=False)
    op.create_index(op.f("ix_surveys_status"), "surveys", ["status"], unique=False)
    op.create_index(op.f("ix_surveys_tender_id"), "surveys", ["tender_id"], unique=False)
    op.create_table(
        "survey_areas",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("tower", sa.String(length=60), nullable=True),
        sa.Column("floor_label", sa.String(length=60), nullable=True),
        sa.Column("floor_no", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column("shape", sa.String(length=8), server_default="rect", nullable=False),
        sa.Column("length_m", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("width_m", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("polygon_m", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("direct_area_sqm", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column(
            "deductions_sqm", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column("perimeter_m", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("perimeter_manual", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "upturn_mm", sa.Numeric(precision=7, scale=1), server_default="0", nullable=False
        ),
        sa.Column("wall_height_m", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("sunk_depth_mm", sa.Numeric(precision=7, scale=1), nullable=True),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("wastage_override_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("method", sa.String(length=8), server_default="manual", nullable=False),
        sa.Column("accuracy_note", sa.String(length=300), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column("camera_method", sa.String(length=8), nullable=True),
        sa.Column("camera_floor_sqm", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("camera_polygon_m", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "floor_area_sqm", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "upturn_area_sqm", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "wall_area_sqm", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "sunk_area_sqm", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "treated_area_sqm",
            sa.Numeric(precision=12, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column("ai_suggestion", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "camera_method IS NULL OR camera_method IN ('ar', 'marker')",
            name=op.f("ck_survey_areas_camera_valid"),
        ),
        sa.CheckConstraint(
            "method IN ('laser', 'manual', 'ar', 'marker', 'cad', 'label')",
            name=op.f("ck_survey_areas_method_valid"),
        ),
        sa.CheckConstraint(
            "shape IN ('rect', 'polygon', 'direct')", name=op.f("ck_survey_areas_shape_valid")
        ),
        sa.CheckConstraint("count >= 1", name=op.f("ck_survey_areas_count_positive")),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_types.id"],
            name=op.f("fk_survey_areas_area_type_id_area_types"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_survey_areas_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["site_nodes.id"],
            name=op.f("fk_survey_areas_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["surveys.id"],
            name=op.f("fk_survey_areas_survey_id_surveys"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
            name=op.f("fk_survey_areas_system_id_systems"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_areas")),
    )
    op.create_index(op.f("ix_survey_areas_node_id"), "survey_areas", ["node_id"], unique=False)
    op.create_index(op.f("ix_survey_areas_survey_id"), "survey_areas", ["survey_id"], unique=False)
    op.create_table(
        "survey_boq_links",
        sa.Column("boq_line_id", sa.BigInteger(), nullable=False),
        sa.Column("survey_area_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boq_line_id"],
            ["boq_lines.id"],
            name=op.f("fk_survey_boq_links_boq_line_id_boq_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["survey_area_id"],
            ["survey_areas.id"],
            name=op.f("fk_survey_boq_links_survey_area_id_survey_areas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("boq_line_id", "survey_area_id", name=op.f("pk_survey_boq_links")),
    )
    op.create_index(
        op.f("ix_survey_boq_links_survey_area_id"),
        "survey_boq_links",
        ["survey_area_id"],
        unique=False,
    )
    op.create_table(
        "survey_photos",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("survey_area_id", sa.BigInteger(), nullable=False),
        sa.Column("stored_path", sa.String(length=400), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("overlay_path", sa.String(length=400), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lat", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("lng", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("gps_accuracy_m", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("device", sa.String(length=200), nullable=True),
        sa.Column("browser", sa.String(length=300), nullable=True),
        sa.Column("tilt_beta", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("tilt_gamma", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("zoom", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("mode", sa.String(length=10), nullable=True),
        sa.Column("marker_found", sa.Boolean(), nullable=True),
        sa.Column("blur_score", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("brightness", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_survey_photos_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["survey_area_id"],
            ["survey_areas.id"],
            name=op.f("fk_survey_photos_survey_area_id_survey_areas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_photos")),
    )
    op.create_index(
        op.f("ix_survey_photos_survey_area_id"), "survey_photos", ["survey_area_id"], unique=False
    )
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("survey_area_id", sa.BigInteger(), nullable=True),
        sa.Column("photo_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=6), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "cost_inr", sa.Numeric(precision=10, scale=4), server_default="0", nullable=False
        ),
        sa.Column("suggestion", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("accepted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ok', 'error')", name=op.f("ck_ai_calls_status_valid")),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["survey_photos.id"],
            name=op.f("fk_ai_calls_photo_id_survey_photos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["survey_area_id"],
            ["survey_areas.id"],
            name=op.f("fk_ai_calls_survey_area_id_survey_areas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_calls_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_calls")),
    )
    op.create_index(op.f("ix_ai_calls_created_at"), "ai_calls", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_ai_calls_survey_area_id"), "ai_calls", ["survey_area_id"], unique=False
    )
    op.add_column("products", sa.Column("pack_unit", sa.String(length=20), nullable=True))
    op.add_column(
        "users", sa.Column("measure_unit", sa.String(length=4), server_default="m", nullable=False)
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "measure_unit")
    op.drop_column("products", "pack_unit")
    op.drop_index(op.f("ix_ai_calls_survey_area_id"), table_name="ai_calls")
    op.drop_index(op.f("ix_ai_calls_created_at"), table_name="ai_calls")
    op.drop_table("ai_calls")
    op.drop_index(op.f("ix_survey_photos_survey_area_id"), table_name="survey_photos")
    op.drop_table("survey_photos")
    op.drop_index(op.f("ix_survey_boq_links_survey_area_id"), table_name="survey_boq_links")
    op.drop_table("survey_boq_links")
    op.drop_index(op.f("ix_survey_areas_survey_id"), table_name="survey_areas")
    op.drop_index(op.f("ix_survey_areas_node_id"), table_name="survey_areas")
    op.drop_table("survey_areas")
    op.drop_index(op.f("ix_surveys_tender_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_status"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_site_id"), table_name="surveys")
    op.drop_index(op.f("ix_surveys_lead_id"), table_name="surveys")
    op.drop_table("surveys")
    op.drop_table("area_types")
    op.drop_table("survey_settings")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("survey.view", "survey", "See site surveys and their quantities"),
    (
        "survey.edit",
        "survey",
        "Create surveys, measure areas, make BOQ lines and indents from them",
    ),
    ("survey.approve", "survey", "Approve a submitted survey"),
    ("survey.ai", "survey", "Ask the AI for a suggestion from an area photo"),
]
GRANTS = {
    "super_admin": dict.fromkeys([c for c, _, _ in NEW_PERMISSIONS], "all"),
    "office_admin": dict.fromkeys([c for c, _, _ in NEW_PERMISSIONS], "all"),
    "estimator": {"survey.view": "all", "survey.edit": "all"},
    "site_supervisor": {"survey.view": "assigned", "survey.edit": "assigned"},
    "sales": {"survey.view": "own", "survey.edit": "own"},
}
# name, upturn mm, includes walls, needs sunk depth, keywords that pick a matching system
AREA_TYPES = [
    ("Terrace", 300, False, False, ["terrace"]),
    ("Toilet / bathroom", 300, False, False, ["toilet", "bathroom"]),
    ("Kitchen", 300, False, False, ["kitchen"]),
    ("Balcony", 300, False, False, ["balcony"]),
    ("Sunken slab", 300, False, True, ["sunken"]),
    ("Basement raft", 0, False, False, ["raft"]),
    ("Basement retaining wall", 0, True, False, ["retaining"]),
    ("Lift pit", 0, True, False, ["lift pit"]),
    ("Underground water tank", 0, True, False, ["underground", "ug tank", "sump"]),
    ("Overhead water tank", 0, True, False, ["overhead", "oh tank"]),
    ("Podium / planter", 0, True, False, ["podium", "planter"]),
    ("External wall", 0, True, False, ["external wall", "exterior wall"]),
    ("Swimming pool", 0, True, False, ["swimming pool", "pool"]),
]


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            op.execute(
                "INSERT INTO role_permissions (role_id, permission_code, scope) "
                f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
                f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
            )
    op.execute("INSERT INTO survey_settings (id) VALUES (1)")
    op.create_check_constraint("measure_unit_valid", "users", "measure_unit IN ('m', 'ftin')")
    bind = op.get_bind()
    systems = bind.execute(sa.text("SELECT id, lower(name) FROM systems WHERE is_active")).all()
    for order, (name, upturn, walls, sunk, keywords) in enumerate(AREA_TYPES, 1):
        # a default system only where exactly one active system clearly matches by name
        matches = {sid for sid, sname in systems if any(k in sname for k in keywords)}
        bind.execute(
            sa.text(
                "INSERT INTO area_types (name, default_system_id, default_upturn_mm, "
                "includes_walls, "
                "needs_sunk_depth, sort_order) VALUES (:n, :s, :u, :w, :d, :o)"
            ),
            {
                "n": name,
                "s": matches.pop() if len(matches) == 1 else None,
                "u": upturn,
                "w": walls,
                "d": sunk,
                "o": order,
            },
        )


def _unseed() -> None:
    op.drop_constraint(op.f("ck_users_measure_unit_valid"), "users", type_="check")
    op.execute(
        "DELETE FROM permissions WHERE code IN ("
        + ", ".join(f"'{c}'" for c, _, _ in NEW_PERMISSIONS)
        + ")"
    )
