"""Quotations: techno-commercial offers and their libraries (letterheads, letter templates,
specification blocks, offer lines, offer items, references, library versions), quotation
revisions with items, lines, issued files and follow-ups; quotation settings; lead activity
attachments; the overdue follow-up alert; quotation permissions.

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-09 07:43:18.495699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "letter_templates",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("opening", sa.Text(), server_default="", nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("enclosures", sa.Text(), server_default="", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_letter_templates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_letter_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_letter_templates_name")),
    )
    op.create_table(
        "library_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('letterhead', 'letter', 'spec', 'line', 'item', 'reference')",
            name=op.f("ck_library_versions_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_library_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_versions")),
        sa.UniqueConstraint("kind", "entity_id", "version", name=op.f("uq_library_versions_kind")),
    )
    op.create_index(
        op.f("ix_library_versions_entity_id"), "library_versions", ["entity_id"], unique=False
    )
    op.create_table(
        "letterheads",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=False),
        sa.Column("logo_path", sa.String(length=300), nullable=True),
        sa.Column("header_text", sa.Text(), nullable=True),
        sa.Column("footer_text", sa.Text(), nullable=True),
        sa.Column("signatory_firm", sa.String(length=200), nullable=False),
        sa.Column("signatory_name", sa.String(length=200), nullable=True),
        sa.Column("signatory_designation", sa.String(length=200), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("primary_color", sa.String(length=7), server_default="#0F6E5A", nullable=False),
        sa.Column("accent_color", sa.String(length=7), server_default="#E69F00", nullable=False),
        sa.Column("tc_template_id", sa.Integer(), nullable=True),
        sa.Column("letter_template_id", sa.Integer(), nullable=True),
        sa.Column("references_state", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_letterheads_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["letter_template_id"],
            ["letter_templates.id"],
            name=op.f("fk_letterheads_letter_template_id_letter_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tc_template_id"],
            ["tc_templates.id"],
            name=op.f("fk_letterheads_tc_template_id_tc_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_letterheads")),
        sa.UniqueConstraint("name", name=op.f("uq_letterheads_name")),
    )
    op.create_table(
        "offer_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("uom", sa.String(length=10), nullable=False),
        sa.Column("rate_source", sa.String(length=10), server_default="fixed", nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("library_item_id", sa.BigInteger(), nullable=True),
        sa.Column("default_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("if_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("client_scope", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "rate_source IN ('system', 'library', 'fixed')",
            name=op.f("ck_offer_lines_rate_source_valid"),
        ),
        sa.CheckConstraint(
            "uom IN ('sqm', 'sqft', 'rft', 'rmt', 'nos', 'kg', 'ltr', 'ls')",
            name=op.f("ck_offer_lines_uom_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_offer_lines_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["library_item_id"],
            ["library_items.id"],
            name=op.f("fk_offer_lines_library_item_id_library_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
            name=op.f("fk_offer_lines_system_id_systems"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_lines")),
    )
    op.create_table(
        "quotation_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("default_validity_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column(
            "followup_days",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[2, 7, 15, 30]",
            nullable=False,
        ),
        sa.Column(
            "closure_target_percent",
            sa.Numeric(precision=5, scale=2),
            server_default="65",
            nullable=False,
        ),
        sa.Column(
            "closure_targets",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("default_letterhead_id", sa.Integer(), nullable=True),
        sa.Column("word_template_path", sa.String(length=300), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_letterhead_id"],
            ["letterheads.id"],
            name=op.f("fk_quotation_settings_default_letterhead_id_letterheads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_settings")),
    )
    op.create_table(
        "offer_items",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column("budget_title", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_types.id"],
            name=op.f("fk_offer_items_area_type_id_area_types"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_offer_items_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_items")),
    )
    op.create_table(
        "quotation_references",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("client_name", sa.String(length=300), nullable=False),
        sa.Column("project", sa.Text(), nullable=False),
        sa.Column("application", sa.Text(), nullable=False),
        sa.Column("area_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("area_unit", sa.String(length=10), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column(
            "area_type_ids", postgresql.ARRAY(sa.Integer()), server_default="{}", nullable=False
        ),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("include", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source", sa.String(length=10), server_default="manual", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "source IN ('site', 'manual', 'imported')",
            name=op.f("ck_quotation_references_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_quotation_references_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_quotation_references_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_references")),
        sa.UniqueConstraint("site_id", name=op.f("uq_quotation_references_site_id")),
    )
    op.create_index(
        op.f("ix_quotation_references_state"), "quotation_references", ["state"], unique=False
    )
    op.create_table(
        "spec_blocks",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "heading_prefix",
            sa.String(length=100),
            server_default="TECHNICAL SPECIFICATION FOR",
            nullable=False,
        ),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("option_label", sa.String(length=20), nullable=True),
        sa.Column(
            "sections", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "images", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_types.id"],
            name=op.f("fk_spec_blocks_area_type_id_area_types"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_spec_blocks_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
            name=op.f("fk_spec_blocks_system_id_systems"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spec_blocks")),
    )
    op.create_table(
        "offer_item_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("offer_line_id", sa.Integer(), nullable=False),
        sa.Column("option", sa.String(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["offer_items.id"],
            name=op.f("fk_offer_item_lines_item_id_offer_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["offer_line_id"],
            ["offer_lines.id"],
            name=op.f("fk_offer_item_lines_offer_line_id_offer_lines"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_item_lines")),
    )
    op.create_index(
        op.f("ix_offer_item_lines_item_id"), "offer_item_lines", ["item_id"], unique=False
    )
    op.create_table(
        "offer_item_specs",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("spec_block_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["offer_items.id"],
            name=op.f("fk_offer_item_specs_item_id_offer_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spec_block_id"],
            ["spec_blocks.id"],
            name=op.f("fk_offer_item_specs_spec_block_id_spec_blocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_item_specs")),
    )
    op.create_index(
        op.f("ix_offer_item_specs_item_id"), "offer_item_specs", ["item_id"], unique=False
    )
    op.create_table(
        "quotations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_latest", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("previous_id", sa.Integer(), nullable=True),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("survey_id", sa.Integer(), nullable=True),
        sa.Column("tender_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("letterhead_id", sa.Integer(), nullable=True),
        sa.Column("salesperson_id", sa.UUID(), nullable=True),
        sa.Column("client_firm", sa.String(length=300), nullable=False),
        sa.Column("client_city", sa.String(length=100), nullable=True),
        sa.Column("client_state", sa.String(length=100), nullable=True),
        sa.Column("attention", sa.String(length=200), nullable=True),
        sa.Column("project", sa.String(length=300), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("areas_list", sa.String(length=300), nullable=True),
        sa.Column("quote_date", sa.Date(), nullable=False),
        sa.Column("validity_days", sa.Integer(), server_default="30", nullable=False),
        sa.Column("status", sa.String(length=12), server_default="draft", nullable=False),
        sa.Column("lost_reason", sa.String(length=20), nullable=True),
        sa.Column("lost_note", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("show_amounts", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("letter_template_id", sa.Integer(), nullable=True),
        sa.Column("opening", sa.Text(), server_default="", nullable=False),
        sa.Column("subject", sa.Text(), server_default="", nullable=False),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("enclosures", sa.Text(), server_default="", nullable=False),
        sa.Column("signatory_name", sa.String(length=200), nullable=True),
        sa.Column("signatory_designation", sa.String(length=200), nullable=True),
        sa.Column(
            "terms", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "references",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("references_title", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "lost_reason IS NULL OR lost_reason IN "
            "('price', 'competitor', 'timing', 'spec', 'relationship', 'other')",
            name=op.f("ck_quotations_lost_reason_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'lost' OR lost_reason IS NOT NULL",
            name=op.f("ck_quotations_lost_needs_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'negotiation', 'won', 'lost', 'expired')",
            name=op.f("ck_quotations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_quotations_client_id_clients"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_quotations_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_quotations_lead_id_leads"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["letter_template_id"],
            ["letter_templates.id"],
            name=op.f("fk_quotations_letter_template_id_letter_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["letterhead_id"],
            ["letterheads.id"],
            name=op.f("fk_quotations_letterhead_id_letterheads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_id"],
            ["quotations.id"],
            name=op.f("fk_quotations_previous_id_quotations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["salesperson_id"],
            ["users.id"],
            name=op.f("fk_quotations_salesperson_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_quotations_site_id_sites"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["surveys.id"],
            name=op.f("fk_quotations_survey_id_surveys"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
            name=op.f("fk_quotations_tender_id_tenders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotations")),
        sa.UniqueConstraint("code", "revision", name=op.f("uq_quotations_code")),
    )
    op.create_index(op.f("ix_quotations_code"), "quotations", ["code"], unique=False)
    op.create_index(op.f("ix_quotations_lead_id"), "quotations", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_quotations_salesperson_id"), "quotations", ["salesperson_id"], unique=False
    )
    op.create_index(op.f("ix_quotations_status"), "quotations", ["status"], unique=False)
    op.create_table(
        "quotation_files",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=4), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("file_name", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('docx', 'pdf')", name=op.f("ck_quotation_files_kind_valid")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_quotation_files_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_quotation_files_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_files")),
    )
    op.create_index(
        op.f("ix_quotation_files_quotation_id"), "quotation_files", ["quotation_id"], unique=False
    )
    op.create_table(
        "quotation_followups",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("salesperson_id", sa.UUID(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'done', 'cancelled')",
            name=op.f("ck_quotation_followups_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_quotation_followups_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["salesperson_id"],
            ["users.id"],
            name=op.f("fk_quotation_followups_salesperson_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_followups")),
    )
    op.create_index(
        op.f("ix_quotation_followups_due_on"), "quotation_followups", ["due_on"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_followups_quotation_id"),
        "quotation_followups",
        ["quotation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quotation_followups_salesperson_id"),
        "quotation_followups",
        ["salesperson_id"],
        unique=False,
    )
    op.create_table(
        "quotation_items",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=False),
        sa.Column("offer_item_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("budget_title", sa.Text(), nullable=False),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "options", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "specs", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_types.id"],
            name=op.f("fk_quotation_items_area_type_id_area_types"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["offer_item_id"],
            ["offer_items.id"],
            name=op.f("fk_quotation_items_offer_item_id_offer_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_quotation_items_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_items")),
    )
    op.create_index(
        op.f("ix_quotation_items_quotation_id"), "quotation_items", ["quotation_id"], unique=False
    )
    op.create_table(
        "quotation_lines",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("offer_line_id", sa.Integer(), nullable=True),
        sa.Column("library_version", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("option", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("uom", sa.String(length=10), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rate_source", sa.String(length=20), nullable=True),
        sa.Column("rate_note", sa.Text(), nullable=True),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("library_item_id", sa.BigInteger(), nullable=True),
        sa.Column("cost_rate", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("margin_percent", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("overridden", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("if_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("client_scope", sa.Boolean(), server_default="false", nullable=False),
        sa.CheckConstraint(
            "uom IN ('sqm', 'sqft', 'rft', 'rmt', 'nos', 'kg', 'ltr', 'ls')",
            name=op.f("ck_quotation_lines_uom_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["quotation_items.id"],
            name=op.f("fk_quotation_lines_item_id_quotation_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["library_item_id"],
            ["library_items.id"],
            name=op.f("fk_quotation_lines_library_item_id_library_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["offer_line_id"],
            ["offer_lines.id"],
            name=op.f("fk_quotation_lines_offer_line_id_offer_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
            name=op.f("fk_quotation_lines_system_id_systems"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotation_lines")),
    )
    op.create_index(
        op.f("ix_quotation_lines_item_id"), "quotation_lines", ["item_id"], unique=False
    )
    op.add_column("lead_activities", sa.Column("quotation_file_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lead_activities_quotation_file_id_quotation_files"),
        "lead_activities",
        "quotation_files",
        ["quotation_file_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_lead_activities_quotation_file_id_quotation_files"),
        "lead_activities",
        type_="foreignkey",
    )
    op.drop_column("lead_activities", "quotation_file_id")
    op.drop_index(op.f("ix_quotation_lines_item_id"), table_name="quotation_lines")
    op.drop_table("quotation_lines")
    op.drop_index(op.f("ix_quotation_items_quotation_id"), table_name="quotation_items")
    op.drop_table("quotation_items")
    op.drop_index(op.f("ix_quotation_followups_salesperson_id"), table_name="quotation_followups")
    op.drop_index(op.f("ix_quotation_followups_quotation_id"), table_name="quotation_followups")
    op.drop_index(op.f("ix_quotation_followups_due_on"), table_name="quotation_followups")
    op.drop_table("quotation_followups")
    op.drop_index(op.f("ix_quotation_files_quotation_id"), table_name="quotation_files")
    op.drop_table("quotation_files")
    op.drop_index(op.f("ix_quotations_status"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_salesperson_id"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_lead_id"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_code"), table_name="quotations")
    op.drop_table("quotations")
    op.drop_index(op.f("ix_offer_item_specs_item_id"), table_name="offer_item_specs")
    op.drop_table("offer_item_specs")
    op.drop_index(op.f("ix_offer_item_lines_item_id"), table_name="offer_item_lines")
    op.drop_table("offer_item_lines")
    op.drop_table("spec_blocks")
    op.drop_index(op.f("ix_quotation_references_state"), table_name="quotation_references")
    op.drop_table("quotation_references")
    op.drop_table("offer_items")
    op.drop_table("quotation_settings")
    op.drop_table("offer_lines")
    op.drop_table("letterheads")
    op.drop_index(op.f("ix_library_versions_entity_id"), table_name="library_versions")
    op.drop_table("library_versions")
    op.drop_table("letter_templates")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("quotation.view", "quotation", "See quotations (techno-commercial offers)"),
    ("quotation.edit", "quotation", "Build and change quotations and their revisions"),
    ("quotation.send", "quotation", "Issue and send quotations, mark them won or lost"),
    (
        "quotation.template.edit",
        "quotation",
        "Change the quotation libraries and save quotation text back to them",
    ),
]
GRANTS = {
    "super_admin": dict.fromkeys([c for c, _, _ in NEW_PERMISSIONS], "all"),
    "office_admin": dict.fromkeys([c for c, _, _ in NEW_PERMISSIONS], "all"),
    "estimator": {"quotation.view": "all", "quotation.edit": "all"},
    "sales": {"quotation.view": "own", "quotation.edit": "own", "quotation.send": "own"},
}
OLD_ACTIVITY_TYPES = ("note", "call", "visit", "status_change", "kylas")
OLD_ALERT_RULES = (
    "dpr_missing",
    "behind_schedule",
    "budget_head",
    "invoice_overdue",
    "po_late",
    "low_stock",
    "petty_negative",
    "tender_due",
    "kylas_failing",
)
# a plain, invented starting letter (the import adds the company's own wording)
STANDARD_LETTER = {
    "name": "Standard offer letter",
    "opening": "Date: **{date}**\nFirm Name: **{client_firm}**\n**{client_city}**\n"
    "Kind Attn.: **{attention}**\n\nDear Sir,",
    "subject": "SUB: OFFER FOR {areas_list} WATERPROOFING WORK.",
    "body": "Reference to the subject, we are submitting herewith our offer for waterproofing work "
    "using **{brand}** products at **{project}**, along with the technical submission "
    "(application methodology, data sheets, etc.).\nPlease contact us for any information or "
    "clarification required.\nWe hope you will find this offer in line with your requirement "
    "and look forward to your valued order.\nThanking you.",
    "enclosures": "Technical Specification\nBudgetary Offer",
}


def _in(values) -> str:
    return ", ".join(f"'{v}'" for v in values)


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            op.execute(
                "INSERT INTO role_permissions (role_id, permission_code, scope) "
                f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
                f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
            )
    op.drop_constraint(op.f("ck_lead_activities_type_valid"), "lead_activities", type_="check")
    op.create_check_constraint(
        "type_valid", "lead_activities", f"type IN ({_in(OLD_ACTIVITY_TYPES + ('quotation',))})"
    )
    op.drop_constraint(op.f("ck_alerts_rule_valid"), "alerts", type_="check")
    op.create_check_constraint(
        "rule_valid", "alerts", f"rule IN ({_in(OLD_ALERT_RULES + ('followup_overdue',))})"
    )
    bind = op.get_bind()
    letter_id = bind.execute(
        sa.text(
            "INSERT INTO letter_templates (name, opening, subject, body, enclosures) "
            "VALUES (:name, :opening, :subject, :body, :enclosures) RETURNING id"
        ),
        STANDARD_LETTER,
    ).scalar()
    profile = bind.execute(
        sa.text("SELECT legal_name, logo_path FROM company_profile WHERE id = 1")
    ).first()
    legal = (profile.legal_name if profile else None) or "Ethios Enviro Solutions Pvt. Ltd."
    tc = bind.execute(sa.text("SELECT id FROM tc_templates WHERE is_default LIMIT 1")).scalar()
    head_id = bind.execute(
        sa.text(
            "INSERT INTO letterheads (name, company_name, logo_path, signatory_firm, "
            "tc_template_id, letter_template_id) VALUES ('EESPL', :c, :logo, :sig, :tc, :lt) "
            "RETURNING id"
        ),
        {
            "c": legal,
            "logo": profile.logo_path if profile else None,
            "sig": f"For {legal.upper()}",
            "tc": tc,
            "lt": letter_id,
        },
    ).scalar()
    bind.execute(
        sa.text("INSERT INTO quotation_settings (id, default_letterhead_id) VALUES (1, :h)"),
        {"h": head_id},
    )


def _unseed() -> None:
    op.execute("DELETE FROM alerts WHERE rule = 'followup_overdue'")
    op.drop_constraint(op.f("ck_alerts_rule_valid"), "alerts", type_="check")
    op.create_check_constraint("rule_valid", "alerts", f"rule IN ({_in(OLD_ALERT_RULES)})")
    op.execute("DELETE FROM lead_activities WHERE type = 'quotation'")
    op.drop_constraint(op.f("ck_lead_activities_type_valid"), "lead_activities", type_="check")
    op.create_check_constraint(
        "type_valid", "lead_activities", f"type IN ({_in(OLD_ACTIVITY_TYPES)})"
    )
    op.execute(
        "DELETE FROM permissions WHERE code IN ("
        + ", ".join(f"'{c}'" for c, _, _ in NEW_PERMISSIONS)
        + ")"
    )
