"""Quotations review: re-issued files (replaced), image letterheads (header, footer, watermark,
pre-printed paper), spec block sub-headings, offer presets (a library kind with versions);
"work front ready" on site structure nodes.

Revision ID: 0025
Revises: 0024
Create Date: 2026-10-09 09:48:05.859985

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

KINDS = "'letterhead', 'letter', 'spec', 'line', 'item', 'reference'"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_presets",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("letterhead_id", sa.Integer(), nullable=True),
        sa.Column("letter_template_id", sa.Integer(), nullable=True),
        sa.Column("tc_template_id", sa.Integer(), nullable=True),
        sa.Column(
            "items", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("include_references", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("needs_check", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_offer_presets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["letter_template_id"],
            ["letter_templates.id"],
            name=op.f("fk_offer_presets_letter_template_id_letter_templates"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["letterhead_id"],
            ["letterheads.id"],
            name=op.f("fk_offer_presets_letterhead_id_letterheads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tc_template_id"],
            ["tc_templates.id"],
            name=op.f("fk_offer_presets_tc_template_id_tc_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_presets")),
        sa.UniqueConstraint("name", name=op.f("uq_offer_presets_name")),
    )
    op.add_column(
        "letterheads", sa.Column("header_image_path", sa.String(length=300), nullable=True)
    )
    op.add_column(
        "letterheads", sa.Column("footer_image_path", sa.String(length=300), nullable=True)
    )
    op.add_column("letterheads", sa.Column("watermark_path", sa.String(length=300), nullable=True))
    op.add_column(
        "letterheads", sa.Column("preprinted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("quotation_files", sa.Column("replaced_by_id", sa.Integer(), nullable=True))
    op.add_column(
        "quotation_files", sa.Column("replaced_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_quotation_files_replaced_by_id_quotation_files"),
        "quotation_files",
        "quotation_files",
        ["replaced_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "site_nodes",
        sa.Column("front_ready", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("site_nodes", sa.Column("front_ready_by", sa.UUID(), nullable=True))
    op.add_column(
        "site_nodes", sa.Column("front_ready_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "site_nodes", sa.Column("front_ready_photo", sa.String(length=300), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_site_nodes_front_ready_by_users"),
        "site_nodes",
        "users",
        ["front_ready_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("spec_blocks", sa.Column("subtitle", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_library_versions_kind_valid"), "library_versions", type_="check")
    op.create_check_constraint("kind_valid", "library_versions", f"kind IN ({KINDS}, 'preset')")


def downgrade() -> None:
    op.execute("DELETE FROM library_versions WHERE kind = 'preset'")
    op.drop_constraint(op.f("ck_library_versions_kind_valid"), "library_versions", type_="check")
    op.create_check_constraint("kind_valid", "library_versions", f"kind IN ({KINDS})")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spec_blocks", "subtitle")
    op.drop_constraint(op.f("fk_site_nodes_front_ready_by_users"), "site_nodes", type_="foreignkey")
    op.drop_column("site_nodes", "front_ready_photo")
    op.drop_column("site_nodes", "front_ready_at")
    op.drop_column("site_nodes", "front_ready_by")
    op.drop_column("site_nodes", "front_ready")
    op.drop_constraint(
        op.f("fk_quotation_files_replaced_by_id_quotation_files"),
        "quotation_files",
        type_="foreignkey",
    )
    op.drop_column("quotation_files", "replaced_at")
    op.drop_column("quotation_files", "replaced_by_id")
    op.drop_column("letterheads", "preprinted")
    op.drop_column("letterheads", "watermark_path")
    op.drop_column("letterheads", "footer_image_path")
    op.drop_column("letterheads", "header_image_path")
    op.drop_table("offer_presets")
    # ### end Alembic commands ###
