"""Site control (9 Oct meeting): delivery notes with a receipt link, discrepancies and
debit-note drafts, vendor rate contracts (with versions), ready-to-bill items, new-area requests,
productivity norms, settings; the three-way match block on vendor bills, the rate contract on
PO lines, the labour check on subcontractor bills, the delivery receiver on sites, the place
(or new area) on material issues; new alert rules; site control permissions.

Revision ID: 0026
Revises: 0025
Create Date: 2026-10-09 10:38:30.650207

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0026"
down_revision: str | None = "0025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sitecontrol_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("receipt_link_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("escalate_first_hours", sa.Integer(), server_default="24", nullable=False),
        sa.Column("escalate_second_hours", sa.Integer(), server_default="48", nullable=False),
        sa.Column("planning_user_id", sa.UUID(), nullable=True),
        sa.Column("bill_alert_days", sa.Integer(), server_default="7", nullable=False),
        sa.Column("contract_expiry_days", sa.Integer(), server_default="15", nullable=False),
        sa.Column(
            "productivity_drop_percent",
            sa.Numeric(precision=5, scale=2),
            server_default="20",
            nullable=False,
        ),
        sa.Column(
            "consumption_tolerance_percent",
            sa.Numeric(precision=5, scale=2),
            server_default="15",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["planning_user_id"],
            ["users.id"],
            name=op.f("fk_sitecontrol_settings_planning_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sitecontrol_settings")),
    )
    op.create_table(
        "rate_contracts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("freight_terms", sa.String(length=200), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_till", sa.Date(), nullable=False),
        sa.Column("agreed_by", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("attachment_path", sa.String(length=300), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("valid_till >= valid_from", name=op.f("ck_rate_contracts_period_valid")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_rate_contracts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_rate_contracts_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_rate_contracts_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_contracts")),
    )
    op.create_index(
        op.f("ix_rate_contracts_product_id"), "rate_contracts", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_rate_contracts_vendor_id"), "rate_contracts", ["vendor_id"], unique=False
    )
    op.create_table(
        "productivity_norms",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=True),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column("sqm_per_manday", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "system_id IS NOT NULL OR area_type_id IS NOT NULL",
            name=op.f("ck_productivity_norms_target_set"),
        ),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_types.id"],
            name=op.f("fk_productivity_norms_area_type_id_area_types"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_productivity_norms_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.id"],
            name=op.f("fk_productivity_norms_system_id_systems"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_productivity_norms")),
        sa.UniqueConstraint("area_type_id", name=op.f("uq_productivity_norms_area_type_id")),
        sa.UniqueConstraint("system_id", name=op.f("uq_productivity_norms_system_id")),
    )
    op.create_table(
        "rate_contract_versions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["rate_contracts.id"],
            name=op.f("fk_rate_contract_versions_contract_id_rate_contracts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_rate_contract_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_contract_versions")),
        sa.UniqueConstraint(
            "contract_id", "version", name=op.f("uq_rate_contract_versions_contract_id")
        ),
    )
    op.create_index(
        op.f("ix_rate_contract_versions_contract_id"),
        "rate_contract_versions",
        ["contract_id"],
        unique=False,
    )
    op.create_table(
        "new_area_requests",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("parent_node_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("area_type_id", sa.Integer(), nullable=True),
        sa.Column("approx_sqm", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("photo", sa.String(length=300), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="pending", nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("moved_to_node_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_new_area_requests_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["area_type_id"],
            ["area_types.id"],
            name=op.f("fk_new_area_requests_area_type_id_area_types"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_new_area_requests_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["moved_to_node_id"],
            ["site_nodes.id"],
            name=op.f("fk_new_area_requests_moved_to_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["site_nodes.id"],
            name=op.f("fk_new_area_requests_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_node_id"],
            ["site_nodes.id"],
            name=op.f("fk_new_area_requests_parent_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_new_area_requests_requested_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_new_area_requests_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_new_area_requests")),
    )
    op.create_index(
        op.f("ix_new_area_requests_site_id"), "new_area_requests", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_new_area_requests_status"), "new_area_requests", ["status"], unique=False
    )
    op.create_table(
        "ready_to_bill",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.BigInteger(), nullable=False),
        sa.Column("area_scope_id", sa.BigInteger(), nullable=False),
        sa.Column("stage_template_id", sa.Integer(), nullable=True),
        sa.Column("boq_line_id", sa.BigInteger(), nullable=True),
        sa.Column("contract_line_id", sa.Integer(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("survey_qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("camera_only", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("ra_bill_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("billed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'billed', 'dismissed')", name=op.f("ck_ready_to_bill_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["area_scope_id"],
            ["area_scopes.id"],
            name=op.f("fk_ready_to_bill_area_scope_id_area_scopes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["boq_line_id"],
            ["boq_lines.id"],
            name=op.f("fk_ready_to_bill_boq_line_id_boq_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contract_line_id"],
            ["contract_lines.id"],
            name=op.f("fk_ready_to_bill_contract_line_id_contract_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["site_nodes.id"],
            name=op.f("fk_ready_to_bill_node_id_site_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ra_bill_id"],
            ["ra_bills.id"],
            name=op.f("fk_ready_to_bill_ra_bill_id_ra_bills"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_ready_to_bill_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stage_template_id"],
            ["stage_templates.id"],
            name=op.f("fk_ready_to_bill_stage_template_id_stage_templates"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ready_to_bill")),
    )
    op.create_index(
        op.f("ix_ready_to_bill_area_scope_id"), "ready_to_bill", ["area_scope_id"], unique=False
    )
    op.create_index(op.f("ix_ready_to_bill_site_id"), "ready_to_bill", ["site_id"], unique=False)
    op.create_index(op.f("ix_ready_to_bill_status"), "ready_to_bill", ["status"], unique=False)
    op.create_table(
        "delivery_notes",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("po_id", sa.Integer(), nullable=True),
        sa.Column("transfer_id", sa.Integer(), nullable=True),
        sa.Column("grn_id", sa.Integer(), nullable=True),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=12), server_default="dispatched", nullable=False),
        sa.Column("expected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vehicle_no", sa.String(length=30), nullable=True),
        sa.Column("driver_name", sa.String(length=100), nullable=True),
        sa.Column("driver_phone", sa.String(length=20), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_path", sa.String(length=300), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("receiver_name", sa.String(length=100), nullable=True),
        sa.Column("receiver_phone", sa.String(length=20), nullable=True),
        sa.Column("receiver_user_id", sa.UUID(), nullable=True),
        sa.Column("unlisted_receiver", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("photo_goods", sa.String(length=300), nullable=True),
        sa.Column("photo_challan", sa.String(length=300), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("gps_accuracy_m", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("drop_photo", sa.String(length=300), nullable=True),
        sa.Column("drop_photo_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("drop_photo_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("kind IN ('po', 'transfer')", name=op.f("ck_delivery_notes_kind_valid")),
        sa.CheckConstraint(
            "status IN ('dispatched', 'confirmed', 'short', 'cancelled')",
            name=op.f("ck_delivery_notes_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_delivery_notes_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["drop_photo_by"],
            ["users.id"],
            name=op.f("fk_delivery_notes_drop_photo_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["grn_id"], ["grns.id"], name=op.f("fk_delivery_notes_grn_id_grns"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.id"],
            name=op.f("fk_delivery_notes_po_id_purchase_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["receiver_user_id"],
            ["users.id"],
            name=op.f("fk_delivery_notes_receiver_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_delivery_notes_site_id_sites"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_delivery_notes_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["transfers.id"],
            name=op.f("fk_delivery_notes_transfer_id_transfers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_delivery_notes_vendor_id_vendors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_notes")),
        sa.UniqueConstraint("code", name=op.f("uq_delivery_notes_code")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_delivery_notes_token_hash")),
    )
    op.create_index(op.f("ix_delivery_notes_po_id"), "delivery_notes", ["po_id"], unique=False)
    op.create_index(op.f("ix_delivery_notes_site_id"), "delivery_notes", ["site_id"], unique=False)
    op.create_index(op.f("ix_delivery_notes_status"), "delivery_notes", ["status"], unique=False)
    op.create_index(
        op.f("ix_delivery_notes_transfer_id"), "delivery_notes", ["transfer_id"], unique=False
    )
    op.create_table(
        "debit_notes",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("po_id", sa.Integer(), nullable=True),
        sa.Column("delivery_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="draft", nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False),
        sa.Column(
            "lines", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "status IN ('draft', 'issued', 'cancelled')", name=op.f("ck_debit_notes_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_debit_notes_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["delivery_notes.id"],
            name=op.f("fk_debit_notes_delivery_id_delivery_notes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_orders.id"],
            name=op.f("fk_debit_notes_po_id_purchase_orders"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_debit_notes_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debit_notes")),
        sa.UniqueConstraint("code", name=op.f("uq_debit_notes_code")),
    )
    op.create_table(
        "delivery_note_lines",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("delivery_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("po_line_id", sa.Integer(), nullable=True),
        sa.Column("transfer_line_id", sa.Integer(), nullable=True),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("packs", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("pack_unit", sa.String(length=20), nullable=True),
        sa.Column("received_qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("damaged_qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["delivery_notes.id"],
            name=op.f("fk_delivery_note_lines_delivery_id_delivery_notes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["po_line_id"],
            ["po_lines.id"],
            name=op.f("fk_delivery_note_lines_po_line_id_po_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_delivery_note_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_line_id"],
            ["transfer_lines.id"],
            name=op.f("fk_delivery_note_lines_transfer_line_id_transfer_lines"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_note_lines")),
    )
    op.create_index(
        op.f("ix_delivery_note_lines_delivery_id"),
        "delivery_note_lines",
        ["delivery_id"],
        unique=False,
    )
    op.create_table(
        "delivery_discrepancies",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("delivery_id", sa.Integer(), nullable=False),
        sa.Column("line_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("debit_note_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('short', 'damaged')", name=op.f("ck_delivery_discrepancies_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["debit_note_id"],
            ["debit_notes.id"],
            name=op.f("fk_delivery_discrepancies_debit_note_id_debit_notes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["delivery_notes.id"],
            name=op.f("fk_delivery_discrepancies_delivery_id_delivery_notes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["delivery_note_lines.id"],
            name=op.f("fk_delivery_discrepancies_line_id_delivery_note_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_delivery_discrepancies_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_discrepancies")),
    )
    op.create_index(
        op.f("ix_delivery_discrepancies_delivery_id"),
        "delivery_discrepancies",
        ["delivery_id"],
        unique=False,
    )
    op.add_column("po_lines", sa.Column("contract_id", sa.Integer(), nullable=True))
    op.add_column(
        "po_lines", sa.Column("contract_rate", sa.Numeric(precision=14, scale=4), nullable=True)
    )
    op.add_column("po_lines", sa.Column("rate_reason", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_po_lines_contract_id_rate_contracts"),
        "po_lines",
        "rate_contracts",
        ["contract_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("site_issues", sa.Column("node_id", sa.BigInteger(), nullable=True))
    op.add_column("site_issues", sa.Column("new_area_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_site_issues_node_id_site_nodes"),
        "site_issues",
        "site_nodes",
        ["node_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_site_issues_new_area_id_new_area_requests"),
        "site_issues",
        "new_area_requests",
        ["new_area_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("sites", sa.Column("receiver_name", sa.String(length=100), nullable=True))
    op.add_column("sites", sa.Column("receiver_phone", sa.String(length=20), nullable=True))
    op.add_column(
        "subcon_bills", sa.Column("productivity_status", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "subcon_bills",
        sa.Column("productivity", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("subcon_bills", sa.Column("productivity_override_by", sa.UUID(), nullable=True))
    op.add_column(
        "subcon_bills",
        sa.Column("productivity_override_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("subcon_bills", sa.Column("productivity_override_note", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_subcon_bills_productivity_override_by_users"),
        "subcon_bills",
        "users",
        ["productivity_override_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "vendor_bills",
        sa.Column(
            "blocked_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column("vendor_bills", sa.Column("released_by", sa.UUID(), nullable=True))
    op.add_column(
        "vendor_bills", sa.Column("released_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("vendor_bills", sa.Column("release_reason", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_vendor_bills_released_by_users"),
        "vendor_bills",
        "users",
        ["released_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_vendor_bills_released_by_users"), "vendor_bills", type_="foreignkey"
    )
    op.drop_column("vendor_bills", "release_reason")
    op.drop_column("vendor_bills", "released_at")
    op.drop_column("vendor_bills", "released_by")
    op.drop_column("vendor_bills", "blocked_reasons")
    op.drop_constraint(
        op.f("fk_subcon_bills_productivity_override_by_users"), "subcon_bills", type_="foreignkey"
    )
    op.drop_column("subcon_bills", "productivity_override_note")
    op.drop_column("subcon_bills", "productivity_override_at")
    op.drop_column("subcon_bills", "productivity_override_by")
    op.drop_column("subcon_bills", "productivity")
    op.drop_column("subcon_bills", "productivity_status")
    op.drop_column("sites", "receiver_phone")
    op.drop_column("sites", "receiver_name")
    op.drop_constraint(
        op.f("fk_site_issues_new_area_id_new_area_requests"), "site_issues", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_site_issues_node_id_site_nodes"), "site_issues", type_="foreignkey")
    op.drop_column("site_issues", "new_area_id")
    op.drop_column("site_issues", "node_id")
    op.drop_constraint(
        op.f("fk_po_lines_contract_id_rate_contracts"), "po_lines", type_="foreignkey"
    )
    op.drop_column("po_lines", "rate_reason")
    op.drop_column("po_lines", "contract_rate")
    op.drop_column("po_lines", "contract_id")
    op.drop_index(
        op.f("ix_delivery_discrepancies_delivery_id"), table_name="delivery_discrepancies"
    )
    op.drop_table("delivery_discrepancies")
    op.drop_index(op.f("ix_delivery_note_lines_delivery_id"), table_name="delivery_note_lines")
    op.drop_table("delivery_note_lines")
    op.drop_table("debit_notes")
    op.drop_index(op.f("ix_delivery_notes_transfer_id"), table_name="delivery_notes")
    op.drop_index(op.f("ix_delivery_notes_status"), table_name="delivery_notes")
    op.drop_index(op.f("ix_delivery_notes_site_id"), table_name="delivery_notes")
    op.drop_index(op.f("ix_delivery_notes_po_id"), table_name="delivery_notes")
    op.drop_table("delivery_notes")
    op.drop_index(op.f("ix_ready_to_bill_status"), table_name="ready_to_bill")
    op.drop_index(op.f("ix_ready_to_bill_site_id"), table_name="ready_to_bill")
    op.drop_index(op.f("ix_ready_to_bill_area_scope_id"), table_name="ready_to_bill")
    op.drop_table("ready_to_bill")
    op.drop_index(op.f("ix_new_area_requests_status"), table_name="new_area_requests")
    op.drop_index(op.f("ix_new_area_requests_site_id"), table_name="new_area_requests")
    op.drop_table("new_area_requests")
    op.drop_index(
        op.f("ix_rate_contract_versions_contract_id"), table_name="rate_contract_versions"
    )
    op.drop_table("rate_contract_versions")
    op.drop_table("productivity_norms")
    op.drop_index(op.f("ix_rate_contracts_vendor_id"), table_name="rate_contracts")
    op.drop_index(op.f("ix_rate_contracts_product_id"), table_name="rate_contracts")
    op.drop_table("rate_contracts")
    op.drop_table("sitecontrol_settings")
    # ### end Alembic commands ###


# --- data ----------------------------------------------------------------------------------------

NEW_PERMISSIONS = [
    ("delivery.view", "sitecontrol", "See delivery notes, their receipts and discrepancies"),
    ("delivery.confirm", "sitecontrol", "Confirm a delivery at site (counts and photos)"),
    (
        "delivery.escalate",
        "sitecontrol",
        "Release a vendor bill blocked by the three-way match (with a reason)",
    ),
    ("ratecontract.view", "sitecontrol", "See vendor rate contracts"),
    ("ratecontract.edit", "sitecontrol", "Add and change vendor rate contracts"),
    ("sitearea.approve", "sitecontrol", "Approve or reject new areas asked for from site"),
    (
        "labourcheck.override",
        "sitecontrol",
        "Approve a subcontractor bill flagged for low labour productivity (with a note)",
    ),
]
ALL = [c for c, _, _ in NEW_PERMISSIONS]
GRANTS = {
    "super_admin": dict.fromkeys(ALL, "all"),
    # "all" but the labour check override, which is Sir's decision (super_admin only by default)
    "office_admin": dict.fromkeys([c for c in ALL if c != "labourcheck.override"], "all"),
    "site_supervisor": {"delivery.view": "assigned", "delivery.confirm": "assigned"},
    "store_purchase": {
        "delivery.view": "all",
        "ratecontract.view": "all",
        "ratecontract.edit": "all",
    },
    "accounts": {"delivery.view": "all", "ratecontract.view": "all"},
    "estimator": {"ratecontract.view": "all"},
}
OLD_RULES = (
    "dpr_missing",
    "behind_schedule",
    "budget_head",
    "invoice_overdue",
    "po_late",
    "low_stock",
    "petty_negative",
    "tender_due",
    "kylas_failing",
    "followup_overdue",
)
NEW_RULES = (
    "dn_unconfirmed",
    "dn_escalated",
    "contract_expiring",
    "ready_not_billed",
    "consumption_var",
)


def _in(values) -> str:
    return ", ".join(f"'{v}'" for v in values)


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description}')"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            op.execute(
                "INSERT INTO role_permissions (role_id, permission_code, scope) "
                f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
                f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
            )
    op.execute("INSERT INTO sitecontrol_settings (id) VALUES (1)")
    op.drop_constraint(op.f("ck_alerts_rule_valid"), "alerts", type_="check")
    op.create_check_constraint("rule_valid", "alerts", f"rule IN ({_in(OLD_RULES + NEW_RULES)})")


def _unseed() -> None:
    op.execute(f"DELETE FROM alerts WHERE rule IN ({_in(NEW_RULES)})")
    op.drop_constraint(op.f("ck_alerts_rule_valid"), "alerts", type_="check")
    op.create_check_constraint("rule_valid", "alerts", f"rule IN ({_in(OLD_RULES)})")
    op.execute(f"DELETE FROM permissions WHERE code IN ({_in(ALL)})")
