"""Team roles and workspaces: the planning, billing and site engineer roles (the director came
in 0027), per-person grants, job assignments on a win, the site status board, the measurement
book, site visits, negotiations, tender bidders, the send checklist fields, daily report return,
team settings and the award follow-up and monthly RA alerts.

Revision ID: 0028
Revises: 0027
Create Date: 2026-10-10 07:13:26.190140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0028"
down_revision: str | None = "0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("billing_day", sa.Integer(), server_default="25", nullable=False),
        sa.Column("award_followup_days", sa.Integer(), server_default="60", nullable=False),
        sa.Column(
            "closure_target_percent",
            sa.Numeric(precision=5, scale=2),
            server_default="30",
            nullable=False,
        ),
        sa.Column(
            "allocation_recipients",
            postgresql.ARRAY(sa.UUID()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("allocation_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_settings")),
    )
    op.create_table(
        "tender_bidders",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("tender_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("rate", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("is_winner", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_us", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
            name=op.f("fk_tender_bidders_tender_id_tenders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_bidders")),
    )
    op.create_index(
        op.f("ix_tender_bidders_tender_id"), "tender_bidders", ["tender_id"], unique=False
    )
    op.create_table(
        "user_grants",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "permission_code IN ('tender.margin', 'jobs.assign')",
            name=op.f("ck_user_grants_grantable"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_user_grants_granted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=op.f("fk_user_grants_permission_code_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_grants_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "permission_code", name=op.f("pk_user_grants")),
    )
    op.create_table(
        "site_visits",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("visited_on", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("accuracy_m", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column(
            "photos", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("first_after_win", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_site_visits_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_site_visits_site_id_sites"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_site_visits_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_visits")),
    )
    op.create_index(op.f("ix_site_visits_lead_id"), "site_visits", ["lead_id"], unique=False)
    op.create_index(op.f("ix_site_visits_site_id"), "site_visits", ["site_id"], unique=False)
    op.create_index(op.f("ix_site_visits_user_id"), "site_visits", ["user_id"], unique=False)
    op.create_table(
        "job_assignments",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=True),
        sa.Column("tender_id", sa.Integer(), nullable=True),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=10), server_default="pending", nullable=False),
        sa.Column("salesperson_id", sa.UUID(), nullable=True),
        sa.Column("engineer_id", sa.UUID(), nullable=True),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_visit_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'done')", name=op.f("ck_job_assignments_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_job_assignments_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["engineer_id"],
            ["users.id"],
            name=op.f("fk_job_assignments_engineer_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["first_visit_id"],
            ["site_visits.id"],
            name=op.f("fk_job_assignments_first_visit_id_site_visits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_job_assignments_lead_id_leads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_job_assignments_quotation_id_quotations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["salesperson_id"],
            ["users.id"],
            name=op.f("fk_job_assignments_salesperson_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_job_assignments_site_id_sites"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
            name=op.f("fk_job_assignments_tender_id_tenders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_assignments")),
    )
    op.create_index(op.f("ix_job_assignments_status"), "job_assignments", ["status"], unique=False)
    op.create_table(
        "negotiations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("quotation_id", sa.Integer(), nullable=True),
        sa.Column("tender_id", sa.Integer(), nullable=True),
        sa.Column("asked", sa.Text(), nullable=False),
        sa.Column("given", sa.Text(), nullable=True),
        sa.Column("revision_quotation_id", sa.Integer(), nullable=True),
        sa.Column("tender_revision_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(quotation_id IS NOT NULL)::int + (tender_id IS NOT NULL)::int = 1",
            name=op.f("ck_negotiations_one_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_negotiations_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
            name=op.f("fk_negotiations_quotation_id_quotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["revision_quotation_id"],
            ["quotations.id"],
            name=op.f("fk_negotiations_revision_quotation_id_quotations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tender_id"],
            ["tenders.id"],
            name=op.f("fk_negotiations_tender_id_tenders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tender_revision_id"],
            ["tender_revisions.id"],
            name=op.f("fk_negotiations_tender_revision_id_tender_revisions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_negotiations")),
    )
    op.create_index(
        op.f("ix_negotiations_quotation_id"), "negotiations", ["quotation_id"], unique=False
    )
    op.create_index(op.f("ix_negotiations_tender_id"), "negotiations", ["tender_id"], unique=False)
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("contract_line_id", sa.Integer(), nullable=True),
        sa.Column("node_id", sa.BigInteger(), nullable=True),
        sa.Column("survey_area_id", sa.BigInteger(), nullable=True),
        sa.Column("ready_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("measured_on", sa.Date(), nullable=False),
        sa.Column("measured_by", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "source IN ('laser', 'manual', 'camera', 'client_certified', 'autocad')",
            name=op.f("ck_measurements_source_valid"),
        ),
        sa.CheckConstraint("qty >= 0", name=op.f("ck_measurements_qty_nonnegative")),
        sa.ForeignKeyConstraint(
            ["contract_line_id"],
            ["contract_lines.id"],
            name=op.f("fk_measurements_contract_line_id_contract_lines"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_measurements_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["measured_by"],
            ["users.id"],
            name=op.f("fk_measurements_measured_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["site_nodes.id"],
            name=op.f("fk_measurements_node_id_site_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ready_id"],
            ["ready_to_bill.id"],
            name=op.f("fk_measurements_ready_id_ready_to_bill"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_measurements_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["survey_area_id"],
            ["survey_areas.id"],
            name=op.f("fk_measurements_survey_area_id_survey_areas"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurements")),
    )
    op.create_index(
        op.f("ix_measurements_contract_line_id"), "measurements", ["contract_line_id"], unique=False
    )
    op.create_index(op.f("ix_measurements_site_id"), "measurements", ["site_id"], unique=False)
    op.add_column("boq_lines", sa.Column("manufacturer", sa.String(length=100), nullable=True))
    op.add_column("dprs", sa.Column("return_comment", sa.Text(), nullable=True))
    op.add_column("dprs", sa.Column("returned_by", sa.UUID(), nullable=True))
    op.add_column("dprs", sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        op.f("fk_dprs_returned_by_users"),
        "dprs",
        "users",
        ["returned_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("quotations", sa.Column("guarantee_years", sa.Integer(), nullable=True))
    op.add_column("ra_bill_lines", sa.Column("client_diff_reason", sa.Text(), nullable=True))
    op.add_column("sites", sa.Column("board_status", sa.String(length=20), nullable=True))
    op.add_column("sites", sa.Column("board_updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("sites", sa.Column("board_updated_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_sites_board_updated_by_users"),
        "sites",
        "users",
        ["board_updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("subcon_bills", sa.Column("billing_checked_by", sa.UUID(), nullable=True))
    op.add_column(
        "subcon_bills", sa.Column("billing_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_subcon_bills_billing_checked_by_users"),
        "subcon_bills",
        "users",
        ["billing_checked_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("tenders", sa.Column("guarantee_years", sa.Integer(), nullable=True))
    op.add_column(
        "tenders", sa.Column("award_followup_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("tenders", sa.Column("winner_lead_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tenders_winner_lead_id_leads"),
        "tenders",
        "leads",
        ["winner_lead_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "users",
        sa.Column("closure_target_percent", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    # ### end Alembic commands ###
    _seed()


def downgrade() -> None:
    _unseed()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "closure_target_percent")
    op.drop_constraint(op.f("fk_tenders_winner_lead_id_leads"), "tenders", type_="foreignkey")
    op.drop_column("tenders", "winner_lead_id")
    op.drop_column("tenders", "award_followup_at")
    op.drop_column("tenders", "guarantee_years")
    op.drop_constraint(
        op.f("fk_subcon_bills_billing_checked_by_users"), "subcon_bills", type_="foreignkey"
    )
    op.drop_column("subcon_bills", "billing_checked_at")
    op.drop_column("subcon_bills", "billing_checked_by")
    op.drop_constraint(op.f("fk_sites_board_updated_by_users"), "sites", type_="foreignkey")
    op.drop_column("sites", "board_updated_by")
    op.drop_column("sites", "board_updated_at")
    op.drop_column("sites", "board_status")
    op.drop_column("ra_bill_lines", "client_diff_reason")
    op.drop_column("quotations", "guarantee_years")
    op.drop_constraint(op.f("fk_dprs_returned_by_users"), "dprs", type_="foreignkey")
    op.drop_column("dprs", "returned_at")
    op.drop_column("dprs", "returned_by")
    op.drop_column("dprs", "return_comment")
    op.drop_column("boq_lines", "manufacturer")
    op.drop_index(op.f("ix_measurements_site_id"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_contract_line_id"), table_name="measurements")
    op.drop_table("measurements")
    op.drop_index(op.f("ix_negotiations_tender_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_quotation_id"), table_name="negotiations")
    op.drop_table("negotiations")
    op.drop_index(op.f("ix_job_assignments_status"), table_name="job_assignments")
    op.drop_table("job_assignments")
    op.drop_index(op.f("ix_site_visits_user_id"), table_name="site_visits")
    op.drop_index(op.f("ix_site_visits_site_id"), table_name="site_visits")
    op.drop_index(op.f("ix_site_visits_lead_id"), table_name="site_visits")
    op.drop_table("site_visits")
    op.drop_table("user_grants")
    op.drop_index(op.f("ix_tender_bidders_tender_id"), table_name="tender_bidders")
    op.drop_table("tender_bidders")
    op.drop_table("team_settings")
    # ### end Alembic commands ###


# --- roles and permissions (keep every existing code) --------------------------------------------

NEW_PERMISSIONS = [
    ("leads.allocate", "crm", "Allocate an unassigned enquiry to a salesperson"),
    ("jobs.assign", "planning", "Pick the salesperson and site engineer for a won job"),
    (
        "planning.view",
        "planning",
        "See the site status board, the allocation list and material plans",
    ),
    ("planning.edit", "planning", "Move any site on the status board and send the allocation list"),
    ("measurement.view", "billing", "See the measurement book"),
    ("measurement.edit", "billing", "Add quantities to the measurement book"),
    ("dpr.approve", "execution", "Approve or return supervisors' daily reports"),
    ("labourcheck.check", "billing", "Mark a labour contractor bill checked against the work done"),
    ("sendcheck.override", "tenders", "Send a BOQ or quotation that fails the send checklist"),
    ("scorecard.view", "crm", "See the closure scorecard"),
    ("sitevisit.log", "crm", "Log site visits (date, photos, notes, GPS)"),
    ("grants.manage", "admin", "Allow one person costs and margins, or deciding won jobs"),
]
NEW = [c for c, _m, _d in NEW_PERMISSIONS]

ROLES = {
    "planning": (
        "Planning",
        "Enquiry intake and allocation, the site status board, material planning, new areas, "
        "delivery escalations and award follow-ups (Sr Engineer Billing & Planning).",
    ),
    "billing": (
        "Billing",
        "Measurements, ready-to-bill, RA and final bills, client bill tracking and the labour "
        "bill check (Jr Engineer Billing, Assistant Manager Billing).",
    ),
    "site_engineer": (
        "Site engineer",
        "One or more sites: survey, work fronts, stages, quality checklists, snags, daily report "
        "approval, indents and new areas (Sr / Jr Engineer Site, Project Manager).",
    ),
}


def _all(*codes):
    return dict.fromkeys(codes, "all")


def _assigned(*codes):
    return dict.fromkeys(codes, "assigned")


GRANTS = {
    "super_admin": _all(*NEW),
    "director": _all(*NEW),
    "planning": _all(
        "leads.view", "leads.edit", "leads.allocate", "clients.view", "clients.edit",
        "tender.view", "quotation.view", "survey.view", "library.view", "vendors.view",
        "site.view", "site.update", "planning.view", "planning.edit", "indent.view",
        "indent.create", "store.view", "po.view", "grn.view", "dpr.view", "labour.view",
        "inspection.view", "sitearea.approve", "delivery.view", "ratecontract.view",
        "measurement.view", "dashboard.view", "dashboard.site",
    ),
    "billing": _all(
        "billing.view", "billing.edit", "measurement.view", "measurement.edit", "survey.view",
        "survey.edit", "site.view", "dpr.view", "labour.view", "subcon.view", "inspection.view",
        "labourcheck.check", "clients.view", "tender.view", "library.view", "dashboard.view",
    ),
    "site_engineer": {
        **_assigned(
            "site.view", "site.update", "survey.view", "survey.edit", "dpr.view", "dpr.edit",
            "dpr.approve", "inspection.view", "inspection.edit", "indent.view", "indent.create",
            "delivery.view", "delivery.confirm", "labour.view", "attendance.manage", "store.view",
            "grn.view", "measurement.view", "measurement.edit", "sitevisit.log", "asset.view",
            "portal.manage", "dashboard.site",
        ),
        "library.view": "all",
        "expense.create": "own",
    },
    "sales": {"sitevisit.log": "own", "scorecard.view": "own"},
    # Settings > Roles: office_admin adjusts a role later without a developer
    "office_admin": {"admin.roles": "all"},
}  # fmt: skip

OLD_RULES = (
    "dpr_missing", "behind_schedule", "budget_head", "invoice_overdue", "po_late", "low_stock",
    "petty_negative", "tender_due", "kylas_failing", "followup_overdue", "dn_unconfirmed",
    "dn_escalated", "contract_expiring", "ready_not_billed", "consumption_var",
)  # fmt: skip
NEW_RULES = ("award_followup", "ra_monthly")


def _in(values) -> str:
    return ", ".join(f"'{v}'" for v in values)


def _seed() -> None:
    for code, module, description in NEW_PERMISSIONS:
        op.execute(
            "INSERT INTO permissions (code, module, description) VALUES "
            f"('{code}', '{module}', '{description.replace(chr(39), chr(39) * 2)}')"
        )
    for code, (name, description) in ROLES.items():
        op.execute(
            "INSERT INTO roles (code, name, description, is_system) VALUES "
            f"('{code}', '{name}', '{description.replace(chr(39), chr(39) * 2)}', true)"
        )
    for role, grants in GRANTS.items():
        for code, scope in grants.items():
            op.execute(
                "INSERT INTO role_permissions (role_id, permission_code, scope) "
                f"SELECT id, '{code}', '{scope}' FROM roles WHERE code = '{role}' "
                f"ON CONFLICT (role_id, permission_code) DO UPDATE SET scope = '{scope}'"
            )
    op.execute("INSERT INTO team_settings (id) VALUES (1)")
    op.drop_constraint(op.f("ck_dprs_status_valid"), "dprs", type_="check")
    op.create_check_constraint(
        "status_valid", "dprs", "status IN ('draft', 'submitted', 'acknowledged', 'returned')"
    )
    op.create_check_constraint(
        "board_status_valid",
        "sites",
        "board_status IS NULL OR board_status IN ('upcoming', 'ongoing', 'completed_to_bill')",
    )
    op.drop_constraint(op.f("ck_alerts_rule_valid"), "alerts", type_="check")
    op.create_check_constraint("rule_valid", "alerts", f"rule IN ({_in(OLD_RULES + NEW_RULES)})")


def _unseed() -> None:
    op.execute(f"DELETE FROM alerts WHERE rule IN ({_in(NEW_RULES)})")
    op.drop_constraint(op.f("ck_alerts_rule_valid"), "alerts", type_="check")
    op.create_check_constraint("rule_valid", "alerts", f"rule IN ({_in(OLD_RULES)})")
    op.drop_constraint(op.f("ck_sites_board_status_valid"), "sites", type_="check")
    op.execute("UPDATE dprs SET status = 'submitted' WHERE status = 'returned'")
    op.drop_constraint(op.f("ck_dprs_status_valid"), "dprs", type_="check")
    op.create_check_constraint(
        "status_valid", "dprs", "status IN ('draft', 'submitted', 'acknowledged')"
    )
    op.execute(f"DELETE FROM roles WHERE code IN ({_in(ROLES)})")
    op.execute(f"DELETE FROM permissions WHERE code IN ({_in(NEW)})")
